/* -----------------------------------------------------------------------------
  Filename:    fbl_cfg.h
  Description: Toolversion: 03.01.02.01.10.00.84.01.00.00
               
               Serial Number: CBD1100084
               Customer Info: Chery Quantum Auto Co., Ltd.
                              Magneti Marelli Guangzhou
                              IC
                              Renesas V850E2 Dx4 UPD70F3524 for LL and UPD70F3530 for HL, Green Hills V5.1.7
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyFblCanBase
               
               Configuration   : D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\fbl_gen_cfg\GWM_B037.gny
               
               ECU: 
                       TargetSystem: Hw_V85xFcnCpu
                       Compiler:     GHS
                       Derivates:    Generic
               
               Channel "Channel0":
                       Databasefile: D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\fbl_gen_cfg\GWM_DBC.dbc
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         IPK

  Generated by , 2019-05-17  23:21:19
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__FBL_CFG_H__)
#define __FBL_CFG_H__

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define FBL_ENABLE_SYSTEM_CHECK
#define FBL_DISABLE_FLASHBLOCK_CHECK
#define FBL_ENABLE_DEBUG_STATUS
#define FBL_WATCHDOG_ON
#define FBL_WATCHDOG_TIME                    (200 / FBL_REPEAT_CALL_CYCLE)
#define FBL_HEADER_ADDRESS                   0x00
#define FBL_ENABLE_APPL_TASK
#define FBL_ENABLE_MULTIPLE_MODULES
#define FBL_DIAG_BUFFER_LENGTH               (4092) /*Length of Queue, need to 4-byte alignment */
//#define FBL_DIAG_BUFFER_LENGTH               (4094) /*when IMC tranfer 258 byte,exclude SID and sequence counter*/
#define FBL_DIAG_TIME_P2MAX_DEFAULT_SESSION  (50 / FBL_REPEAT_CALL_CYCLE)
#define FBL_DIAG_TIME_P2MAX                  (25 / FBL_REPEAT_CALL_CYCLE)
#define FBL_DIAG_TIME_P3MAX                  (5000 / FBL_REPEAT_CALL_CYCLE)
#define FBL_DISABLE_SLEEPMODE
#define kFillChar                            0x00
#define FBL_DISABLE_MULTIPLE_MEM_DEVICES
/*  */
/* V850_FCN specific ********************************************************* */
#define FBL_SYSTEM_FREQUENCY                 16
#define FBL_OSCCLK                           16
#define FBL_LENGTH                           0xBC00
#define FLASH_SIZE                           0x3000
#define FBL_TIMER_RELOAD_VALUE               19999
#define FBL_TIMER_PRESCALER                  1
#define FBL_WD_TRIGGER_SIZE                  0x0200
#define CAN_BRP                              0x00
#define CAN_BTR                              0x0104
#define CAN_CS                               0x00
#define FBL_NUMBER_OF_HW_OBJECTS             0x40
#define kFblCanMacroAdr                      0xFF480000
#define FBL_CAN_0
/*  */
#define CAN_TP_FUNC_RXID               0x7FF// 0x18DBFEF1u

/*DDM*/
#if defined(DCM_ZEEKR_DDM)
#define CAN_TP_RXID                   0x730 // 0x18DA6AF1u 0x781 //  0x766
#define CAN_TP_TXID                   0X630  // 0x18DAF16Au   0X681    //0x7a6
#elif defined(DCM_ZEEKR_PDM)
#define CAN_TP_RXID                   0x77B
#define CAN_TP_TXID                   0X67B
#elif defined(DCM_ZEEKR_RLDM)
#define CAN_TP_RXID                   0x7C5
#define CAN_TP_TXID                   0X6C5
#elif defined(DCM_ZEEKR_RRDM)
#define CAN_TP_RXID                   0x7C1
#define CAN_TP_TXID                   0X6C1
#endif






#define FBL_REPEAT_CALL_CYCLE                1
#define FBL_HW_LAST_MASKINT_ADDRESS          0x1070
/* Manufacturer specific part ******************************************************************************** */
/*  */
/*  */
#define FBL_MTAB_NO_OF_BLOCKS                6
/* FBL multiple nodes support: */
#define FBL_DISABLE_MULTIPLE_NODES
/* kNmEcuNr */
#ifdef VGEN_ENABLE_CAN_DRV
#else
#define kNmEcuNr                             0x7FFFFBFF
#endif

/*  */
#define FBL_DISABLE_SWIL_II
#define FBL_DISABLE_GAP_FILL
/*  */
/*  */
#define FBL_DISABLE_ENCRYPTION_MODE
#define FBL_DISABLE_USERSUBFUNCTION
#define FBL_DISABLE_FBL_START
#define SWM_DATA_MAX_NOAR                    30
#define FBL_SLEEP_TIME                       300000
#define FLASHDRIVER_BLOCKINDEX               0x00
#define FBL_SEC_ACCESS_DELAY_TIME            ((vuint32) 10000)
#define FBL_ENABLE_SEC_ACCESS_DELAY
#define FBL_DISABLE_MINIMUM_PROGRAMMING_SEQUENCE
#define FBL_DISABLE_STAY_IN_BOOT
#define FBL_ENABLE_ADDR_BASED_DOWNLOAD


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

/* Enable correct includes for Vector security module */
#define FBL_ENABLE_SECMOD_VECTOR



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 317678191
      #error "The magic number of the generated file <D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\GenData_V850\fbl_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 317678191
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __FBL_CFG_H__ */
