/* -----------------------------------------------------------------------------
  Filename:    Secm_cfg.h
  Description: Toolversion: 03.01.02.01.10.00.84.01.00.00
               
               Serial Number: CBD1100084
               Customer Info: Chery Quantum Auto Co., Ltd.
                              Magneti Marelli Guangzhou
                              IC
                              Renesas V850E2 Dx4 UPD70F3524 for LL and UPD70F3530 for HL, Green Hills V5.1.7
               
               
               Generator Fwk   : GENy 
               Generator Module: FblSecMod_Vector
               
               Configuration   : D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\fbl_gen_cfg\GWM_B037.gny
               
               ECU: 
                       TargetSystem: Hw_V85xFcnCpu
                       Compiler:     GHS
                       Derivates:    Generic
               
               Channel "Channel0":
                       Databasefile: D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\fbl_gen_cfg\GWM_DBC.dbc
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         IPK

  Generated by , 2019-05-17  23:21:19
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__SECM_CFG_H__)
#define __SECM_CFG_H__
#include "can_def.h"

#define SEC_CLASS_DDD                        0
#define SEC_CLASS_C                          1
#define SEC_CLASS_CCC                        2
#define SEC_CLASS_VENDOR                     3
#define SEC_DEVELOPMENT                      1
#define SEC_PRODUCTION                       2
#define SEC_ADDRESS                          1
#define SEC_FILE                             2
#define SEC_CRC_SPEED_OPTIMIZED              0
#define SEC_CRC_SIZE_OPTIMIZED               1
#define SEC_SECURITY_CLASS SEC_CLASS_CCC
#define SEC_ECU_KEY                          0x00
#define SEC_KEY_TIMEOUT                      100
#define SEC_CALL_CYCLE                       10
#define SEC_MEMORY_ACCESS                    SEC_ADDRESS
#define SEC_MODE                             SEC_PRODUCTION
#define SEC_CRC_OPT                          SEC_CRC_SIZE_OPTIMIZED
#define SEC_VER_ENABLE_CRC_TOTAL
#define SEC_RIPEMD160                        0
#define SEC_SHA1                             1
#define SEC_HASH_ALGORITHM                   SEC_SHA1
#define SEC_VERIFY_BYTES                     64
#define SEC_DISABLE_DECRYPTION
#define SEC_VER_ENABLE_LENGTH_AND_ADDRESS_INPUT
#define SECM_VER_SIG_OFFSET                  0
#define SECM_VER_CRC_OFFSET                  0

/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 317678191
      #error "The magic number of the generated file <D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\GenData_V850\Secm_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 317678191
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __SECM_CFG_H__ */
