/* -----------------------------------------------------------------------------
  Filename:    Secmpar.h
  Description: Toolversion: 03.01.02.01.10.00.84.01.00.00
               
               Serial Number: CBD1100084
               Customer Info: Chery Quantum Auto Co., Ltd.
                              Magneti Marelli Guangzhou
                              IC
                              Renesas V850E2 Dx4 UPD70F3524 for LL and UPD70F3530 for HL, Green Hills V5.1.7
               
               
               Generator Fwk   : GENy 
               Generator Module: FblSecMod_Vector
               
               Configuration   : D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\fbl_gen_cfg\GWM_B037.gny
               
               ECU: 
                       TargetSystem: Hw_V85xFcnCpu
                       Compiler:     GHS
                       Derivates:    Generic
               
               Channel "Channel0":
                       Databasefile: D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\fbl_gen_cfg\GWM_DBC.dbc
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         IPK

  Generated by , 2019-05-17  23:21:19
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__SECMPAR_H__)
#define __SECMPAR_H__

#include "secm_inc.h"
#define SECMPAR_START_SEC_DATA
#include "memmap.h"
V_MEMROM0 extern  V_MEMROM1 vuint8 V_MEMROM2 SecM_RsaMod[128];
V_MEMROM0 extern  V_MEMROM1 vuint8 V_MEMROM2 SecM_RsaExp[4];
#define SECMPAR_STOP_SEC_DATA
#include "memmap.h"

/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 317678191
      #error "The magic number of the generated file <D:\Projects\GWM_B037\GWM_B037_IC\GWM_B037_BLF_RH850\GWM_B037_FBL_Cfg\GenData_V850\Secmpar.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 317678191
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __SECMPAR_H__ */
