/* -----------------------------------------------------------------------------
  Filename:    tp_cfg.h
  Description: Toolversion: 03.01.02.01.10.00.84.01.00.00
               
               Serial Number: CBD1100084
               Customer Info: Chery Quantum Auto Co., Ltd.
                              Magneti Marelli Guangzhou
                              IC
                              Renesas V850E2 Dx4 UPD70F3524 for LL and UPD70F3530 for HL, Green Hills V5.1.7
               
               
               Generator Fwk   : GENy 
               Generator Module: Tp_Iso15765
               
               Configuration   : D:\GEELY_PRO\geely_nl3ba1_ic\Geely_NL3BA1_BLF_RH850\Geely_NL3BA1_FBL_Cfg\fbl_gen_cfg\Geely_NL3B.gny
               
               ECU: 
                       TargetSystem: Hw_V85xFcnCpu
                       Compiler:     GHS
                       Derivates:    Generic
               
               Channel "Channel0":
                       Databasefile: D:\mypro\GEELY_FS11_IC\Geely_FS11_BLF_RH850\Geely_FS11_FBL_Cfg\fbl_gen_cfg\Geely_DBC.dbc
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         IPK

  Generated by , 2021-02-25  09:23:35
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__TP_CFG_H__)
#define __TP_CFG_H__
#include "can_def.h"
#include "can_inc.h"
#define TP_MEMORY_MODEL_DATA

#define TP_ENABLE_SINGLE_MSG_OBJ
#define TP_ISO15765DLL_VERSION               0x0231
#define TP_ISO15765DLL_RELEASE_VERSION       0x00

#define kTpNumberOfCanChannels               1
#ifndef kTpOn
#define kTpOn                                1
#endif

#ifndef kTpOff
#define kTpOff                               0
#endif

#define TP_TYPE_MULTI_DYNAMIC_NORMAL_ADDRESSING
struct tTpCopyToCanInfoStruct_s
{
  canuint8                       Channel;     /* TP Channel                           */
  TxDataPtr                      pDestination;/* Pointer to destination buffer        */
  TP_MEMORY_MODEL_DATA canuint8* pSource;     /* Pointer to source buffer (if linear) */
  canuint16                      Length;      /* The maximum length to copy           */
};
typedef struct tTpCopyToCanInfoStruct_s tTpCopyToCanInfoStruct;
typedef struct tTpCopyToCanInfoStruct_s *TpCopyToCanInfoStructPtr;

#define TP_USE_ISO_COMPLIANCE                kTpOn
#define TP_USE_FAST_PRECOPY                  kTpOff
#define TP_USE_DIAGPRECOPY                   kTpOff
#define TP_CAN_CHANNEL_INDEX                 0
#define TP_ENABLE_ISO_15765_2_2
#define TP_DISABLE_ASR_SINGLE_TP
#define TP_DISABLE_OBD_PRECOPY

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_USE_EXTENDED_API_BS               kTpOff
#define TP_USE_EXTENDED_API_STMIN            kTpOff
#define TP_USE_TX_OF_FC_IN_ISR               kTpOn
#define TP_USE_OVERRUN_INDICATION            kTpOff
#define TP_USE_ONLY_FIRST_FC                 kTpOn
#define TP_USE_FAST_TX_TRANSMISSION          kTpOff
#define TP_USE_QUEUE_IN_ISR                  kTpOn
#define TP_USE_NO_STMIN_AFTER_FC             kTpOff
#define MEMORY_NEAR_TP_SAVE                  MEMORY_NEAR
#define TP_USE_TX_HANDLE_CHANGEABLE          kTpOff
#define TP_USE_GATEWAY_API                   kTpOff
#define TP_USE_RX_CHANNEL_WITHOUT_FC         kTpOff
#define TP_USE_TX_CHANNEL_WITHOUT_FC         kTpOff
#define TP_USE_OLD_STMIN_CALCULATION         kTpOff
#define TP_USE_VARIABLE_RX_DLC_CHECK         kTpOn
#define TP_USE_FIX_RX_DLC_CHECK              kTpOff
#define TP_USE_PADDING                       kTpOn
#define TP_PADDING_PATTERN                   0x00 /*PADDING is 0 ON ZEEKR */
#define TP_USE_VARIABLE_DLC                  kTpOff
#define TP_DISABLE_IGNORE_FC_RES_STMIN
#define TP_DISABLE_IGNORE_FC_OVFL
#define TP_DISABLE_WAIT_FOR_CORRECT_SN
#define TP_DISABLE_SINGLE_CHAN_MULTICONN
#define TP_DISABLE_FC_WAIT
#define TP_DISABLE_EXT_COPYFROMCAN_API


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_USE_NORMAL_ADDRESSING             kTpOn
#define TP_USE_NORMAL_FIXED_ADDRESSING       kTpOff
#define TP_USE_EXTENDED_ADDRESSING           kTpOff
#define TP_USE_MIXED_11_ADDRESSING           kTpOff
#define TP_USE_MIXED_29_ADDRESSING           kTpOff
#define TP_DISABLE_SINGLE_CHANNEL_TP
#define TP_DISABLE_MULTIPLE_ADDRESSING
#define TP_DISABLE_MULTIPLE_NODES
#define TP_DISABLE_USER_CHECK
#define TP_DISABLE_INTERNAL_CHECK
#define TP_DISABLE_GEN_CHECK
#define TP_DISABLE_RUNTIME_CHECK


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_USE_PRE_COPY_CHECK                kTpOff

#define TPC_ENABLE_DYN_TX_OBJECTS
#define TPC_ENABLE_DYN_TX_ID
#define TPC_ENABLE_DYN_TX_DLC
#define TPC_DISABLE_DYN_TX_DATAPTR
#define TPC_DISABLE_DYN_TX_PRETRANS_FCT
#define TPC_DISABLE_DYN_TX_CONF_FCT
#define TP_USE_APPL_PRECOPY                  kTpOff
#define TP_USE_FREE_CHANNEL_SEARCH           kTpOn
#define TP_USE_CUSTOM_RX_MEMCPY              kTpOff
#define TP_DISABLE_FUNCTIONAL_FC_WAIT


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_USE_STMIN_OF_FC                   kTpOn
#define TP_USE_TP_TRANSMIT_QUEUE             kTpOn
#define TP_USE_DYN_ID                        kTpOn
#define TP_USE_CUSTOM_TX_MEMCPY              kTpOff


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_USE_WAIT_FRAMES                   kTpOff
#define TP_USE_MULTIPLE_BASEADDRESS          kTpOff
#define TP_USE_PRE_DISPATCHED_MODE           kTpOff


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_USE_EXT_IDS_FOR_NORMAL          kTpOn
#define TP_USE_MIXED_IDS_FOR_NORMAL        kTpOn

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_DISABLE_MIN_TIMER
#define kTpTxChannelCount                    1
#define kTpRxChannelCount                    1

#define TpMemCpy                             memcpy
#define TpTxCallCycle                        1
#define TpRxCallCycle                        1

#define kBSRequested                         0
#define kTpTxConfirmationTimeout             1000*10    /*Tx N_As 1S*/
#define kTpRxConfirmationTimeout             1000*10     /*Rx N_Ar 1S*/
#define TpSTMin                              0
#define TpTxTimeoutFC                        1000*10
#define TpRxTimeoutCF                        1000*10    /*Rx N_Cr 1S*/
#define TpTxTransmitCF                       8*10      /*Tx N_Cs 8mS */
#define TpTxStminParameter                   10        /*1ms */
#define __ApplTpPreCopyCheckFunction(x)
#define __ApplTpPrecopyCheckFCFunctional(tpCurrentTargetAddress)
#define TP_DISABLE_CHECKTA_COMPATIBILITY
#define __ApplTpPrecopy(target)


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define TP_FUNC_ENABLE_RECEPTION
#define TP_FUNC_ENABLE_NORMAL_ADDRESSING
#define TP_FUNC_DISABLE_NORMAL_FIXED_ADDRESSING
#define TP_FUNC_DISABLE_EXTENDED_ADDRESSING
#define TP_FUNC_DISABLE_MIXED_11_ADDRESSING
#define TP_FUNC_DISABLE_MIXED_29_ADDRESSING
#define TP_FUNC_DISABLE_APPL_PRECOPY
#define __ApplTpFuncGetBuffer                FblFuncGetBuffer
canuint8* FblFuncGetBuffer(vuint16 dataLength);
#define __ApplTpFuncIndication               FblFuncReqInd
void FblFuncReqInd(vuint16 dataLength);


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

/*#define kTpDiagFuncRxCanId                   0x07DF*/


#define kTpTxHandle CanTxTxDynamicMsg0

#define kTpTxData TxDynamicMsg0._c


/* function prototypes */
void FblDataInd(canuint8 tpChannel, canuint16 datLen);
void FblTpRxErrorIndication(canuint8 tpChannel, canuint8 errNo);
void FblTpTxConfirmation(canuint8 tpChannel, canuint8 state);
canuint8* FblTpRxGetBuffer( vuint8 tpChannel, vuint16 dataLength, vuint8 *queueNum);
canuint8 FblTpTxErrorIndication(canuint8 tpChannel, canuint8 errNo);

#define __ApplTpRxIndication(tpChannel, datLen) (FblDataInd(tpChannel, datLen))
#define __ApplTpRxErrorIndication(tpChannel, errNo) (FblTpRxErrorIndication(tpChannel, errNo))
#define __ApplTpTxConfirmation(tpChannel, state) (FblTpTxConfirmation(tpChannel, state))
#define __ApplTpRxSF(tpChannel) 
#define __ApplTpRxFF(tpChannel) 
#define __ApplTpRxCF(tpChannel) 
#define __ApplTpTxNotification(tpChannel, datLen) 
#define __ApplTpTxCanMessageTransmitted(tpChannel) 
#define __ApplTpTxFC(tpChannel) 
#define __ApplTpRxGetBuffer(tpChannel, datLen , queueNum) (FblTpRxGetBuffer(tpChannel, datLen, queueNum))
#define __ApplTpTxErrorIndication(tpChannel, errNo) (FblTpTxErrorIndication(tpChannel, errNo))
#define __ApplTpTxCopyToCAN(infoStruct) 
#define __ApplTpRxCopyFromCAN(tpChannel, src, datLen) 
#define __ApplTpRxCanMessageTransmitted(tpChannel) 
#define __ApplTpTxDelayFinished(tpChannel, state) 

#define TpTransmitFblPhys(dataPtr, dataLen) TpTransmit(0, dataPtr, dataLen)

/* Configure multiple nodes */
extern vuint8 fblEcuHandle;
#define vActiveIdentityLog fblEcuHandle


/* end Fileversion check */

#endif /* __TP_CFG_H__ */
