###############################################################################
# File Name  : Makefile_app_modulelist.mk
# Description: All Modules to be builded on Application Project
# Project    : 
# Module     : 
###############################################################################


###############################################################################
# app/core_app/src/
###############################################################################
# 0 : remove from compile
# 1 : include to compile

#------------------------------------------------------------------------------
# app/core_app/src/appl
#------------------------------------------------------------------------------ 
SRC_INCLUDE_SW_SWF=1

#------------------------------------------------------------------------------
# app/core_app/src/bswgen
#------------------------------------------------------------------------------ 

#------------------------------------------------------------------------------
# app/core_app/src/cdd_cfg
#------------------------------------------------------------------------------ 
SRC_INCLUDE_CDD_CFG=1

#------------------------------------------------------------------------------
# app/core_app/src/mcalgen
#------------------------------------------------------------------------------ 

#------------------------------------------------------------------------------
# app/core_app/src/swc_cfg
#------------------------------------------------------------------------------ 
SRC_INCLUDE_SWC_CFG=1

MCAL_EXCLUDE_ADC=1
MCAL_EXCLUDE_DIO=1
MCAL_EXCLUDE_FLS=1
MCAL_EXCLUDE_GPT=1
MCAL_EXCLUDE_ICU=1
MCAL_EXCLUDE_MCU=1
MCAL_EXCLUDE_OCU=1
MCAL_EXCLUDE_PORT=1
MCAL_EXCLUDE_PWM=1
MCAL_EXCLUDE_SPI=1
MCAL_EXCLUDE_WDG=1
MCAL_EXCLUDE_CAN=1
MCAL_EXCLUDE_LIN=1
MCAL_EXCLUDE_UART=1

###############################################################################
# app/core_app/src_platform/
###############################################################################

#------------------------------------------------------------------------------ 
# app/core_app/src_platform/bsw_cbd
#------------------------------------------------------------------------------
MODULE_LIST_PROJECT=Crc                     \
                    Fee_30_FlexNor          \
                    Mcal_Cyt2xy             \
                    Mem_30_LegacyAdapter    \
                    MemAcc                  \
                    MemIf                   \
                    NvMGen2                 \
                    vMem_30_Traveo2Cyp01    

                    
BSW_INCLUDE_GENDATA_FILE=1
BSW_INCLUDE_COMMON_PATH=1

#------------------------------------------------------------------------------
# app/core_app/src_platform/mcal_cypress_traveo2
#------------------------------------------------------------------------------ 

# NOTE: {PROJECT_MODULES} is defined on Make_cfg.mak that is generated by EB Tresos
PROJECT_MODULES = -

MCAL_EXCLUDE_BASE_MODULE=1
MCAL_EXCLUDE_PLATFORMS_MODULE=1

#------------------------------------------------------------------------------
# app/core_app/src_platform/cdd
#------------------------------------------------------------------------------ 

# If you set to:
#    -   : will remove all submodules in this folder from the compile
#    .   : will include all submodules in this folder to compile
#  `cdd` : specify one or more module to compile

# TODO: [ALL] Added the SWC and updated this file too.
CDD_MODULE_LIST_PRJ=CPUS \
                    VERS \
                    TVII_SDL \
                    SYST \
                    TYPE \
                    TARG \
                    SPIC \
                    IODC \
                    IODD \
                    VECD \
                    TPMC \
                    SPID \
                    STAR \


#------------------------------------------------------------------------------
# app/core_app/src_platform/cdd/BCMIo
#------------------------------------------------------------------------------ 

# If you set to:
#    -   : will remove all submodules in this folder from the compile
#    .   : will include all submodules in this folder to compile
#  `cdd` : specify one or more module to compile

# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
# app/core_app/src_platform/cdd/BCMIo/Base
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
CDD_BCMIO_BASE_MODULE_LIST=-
#CDD_BCMIO_BASE_MODULE_LIST=.
#CDD_BCMIO_BASE_MODULE_LIST=CSIOD DMAD EXTD FRTD ICUD INAD LPMD OCUD PPFD PPGD RLTD RTCD SCKD WDTD


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
# app/core_app/src_platform/cdd/BCMIo/Control
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
CDD_BCMIO_CONTROL_MODULE_LIST= 
#CDD_BCMIO_CONTROL_MODULE_LIST=.
#CDD_BCMIO_CONTROL_MODULE_LIST=DMAC EXTC GPTC INAC LPMC PPFC PWMC RFMC SPIC TXPC VSOC VN9C


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
# app/core_app/src_platform/cdd/BCMIo/Presentation
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
CDD_BCMIO_PRESENT_MODULE_LIST= 
#CDD_BCMIO_PRESENT_MODULE_LIST=.
#CDD_BCMIO_PRESENT_MODULE_LIST=BATP CRYP DOUP INAP LINP RFMP TXPP WLIFTP


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
# app/core_app/src_platform/cdd/BCMIo/System
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
CDD_BCMIO_SYSTEM_MODULE_LIST= 
#CDD_BCMIO_SYSTEM_MODULE_LIST=.
#CDD_BCMIO_SYSTEM_MODULE_LIST=BCM_IO TYPE



#------------------------------------------------------------------------------
# app/core_app/src_platform/swc
#------------------------------------------------------------------------------ 

# If you set to:
#    -   : will remove all submodules in this folder from the compile
#    .   : will include all submodules in this folder to compile
#  `swc` : specify one or more module to compile
#SWC_MODULE_LIST_PRJ=-
#SWC_MODULE_LIST_PRJ=.
SWC_MODULE_LIST_PRJ=DEVM \
                    FBLM \
                    SBCM \
                    RSAM \




SWC_STARTUP_EXCLUDE_ALL=1
SWC_ISDL_EXCLUDE_ALL=0

WDF_MODULE_LIST_PRJ= WDFP WDFS 
SWC_WDF_EXCLUDE_ALL=1

#______________________________________________________________________________#
# List of submodules that the optimization must NOT be included during building!
# Please, add '|' instead of space between de module's name
MOD_LIST_WITHOUT_OPTIM_OPT=RFMC|VF606

#______________________________________________________________________________#
