#if !defined( FLS_IRQ_H )
#define FLS_IRQ_H

/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the all interrupt service routines and fault handling
 ** routine declarations for the AUTOSAR module Fls.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */


/*==================[includes]==============================================*/

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#define FLS_START_SEC_CODE
#include <Fls_MemMap.h>
#include "syst_TVII.h"
/** \brief Fls_Isr_Ipc_Cat1
 **
 ** Category 1 interrupt service routine for vector 2 or 3 of flash processing (IPC_INTR).
 **
 ** \return    none
 **
 */
extern ISR_NATIVE(Fls_Isr_Ipc_Cat1);

/** \brief Fls_Isr_Ipc_Cat2
 **
 ** Category 2 interrupt service routine for vector 2 or 3 of flash processing (IPC_INTR).
 **
 ** \return    none
 **
 */
extern ISR(Fls_Isr_Ipc_Cat2);

/** \brief Fls_Isr_Flash_Cat1
 **
 ** Category 1 interrupt service routine for vector 46 of flash processing (FM_CTL_ECT).
 **
 ** \return    none
 **
 */
extern ISR_NATIVE(Fls_Isr_Flash_Cat1);

/** \brief Fls_Isr_Flash_Cat2
 **
 ** Category 2 interrupt service routine for vector 46 of flash processing (FM_CTL_ECT).
 **
 ** \return    none
 **
 */
extern ISR(Fls_Isr_Flash_Cat2);

/** \brief Fls_Fault_Handling
 **
 ** The handling routine of fault for flash memory (FAULT, FLASHC).
 **
 ** \return    none
 **
 */
extern FUNC(void, FLS_CODE) Fls_Fault_Handling(void);

/** \brief Fls_Isr_FlsIpc_Cat1
 **
 ** Category 1 interrupt service routine for vector 7 of IPC for eCT Flash safety mechanism.
 **
 ** \return    none
 **
 */
extern ISR_NATIVE(Fls_Isr_FlsIpc_Cat1);

/** \brief Fls_Isr_FlsIpc_Cat2
 **
 ** Category 2 interrupt service routine for vector 7 of IPC for eCT Flash safety mechanism.
 **
 ** \return    none
 **
 */
extern ISR(Fls_Isr_FlsIpc_Cat2);


#define FLS_STOP_SEC_CODE
#include <Fls_MemMap.h>

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/



#endif /* if !defined( FLS_IRQ_H ) */
/*==================[end of file]===========================================*/
