#if !defined( FLS_PBCFG_H )
#define FLS_PBCFG_H

/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the post-build time configuration declarations for
 ** the AUTOSAR module Fls that are target independent.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[includes]==============================================*/

#include <MemIf_Types.h>           /* AUTOSAR standard types */
#include <ErrorCalloutHandler.h>

/*==================[macros]================================================*/


#define FLS_NUMBER_OF_CONFIGSETS    1U

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

#define FLS_START_SEC_CONST_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/* Deviation from MISRA-C:2004 rule 8.10, MISRA-C:2012 Rule-8.7.
   Justification: This interface is intentionally external scope in order to read
   from outside. */
/* PRQA S 1504 1 */
extern CONST( Fls_ConfigType, FLS_CONST ) Fls_Config_0;

/* Deviation from MISRA-C:2004 rule 8.10, MISRA-C:2012 Rule-8.7.
   Justification: This interface is intentionally external scope in order to read
   from outside. */
/* PRQA S 1504 1 */
extern CONST( Fls_MemoryMapType, FLS_CONST ) Fls_MemoryMap_0[4];


extern CONSTP2CONST(Fls_ConfigType, AUTOMATIC, FLS_APPL_CONST) Fls_ConfigPtrArray[FLS_NUMBER_OF_CONFIGSETS];

extern CONSTP2CONST(Fls_MemoryMapType, AUTOMATIC, FLS_APPL_CONST) Fls_MemoryMapPtrArray[FLS_NUMBER_OF_CONFIGSETS];

#define FLS_STOP_SEC_CONST_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/



#endif /* if !defined( FLS_PBCFG_H ) */
/*==================[end of file]===========================================*/
