/* MISRA RULE 19.15 VIOLATION: The file tcb.h is intentionally included multiple times. 
 * The file consists of multiple parts which are used only if the including file has 
 * set a certain define macro (osdPreTCB/osdPostTCB). Each part has a separate double 
 * include preventer. Typical MISRA checkers will not be able to find these multiple 
 * double include preventers.
 */
/* PRQA S 0883 EOF */
/* file: tcb.h, automatically generated by genRH850as.EXE, Version: 5.02 */
/* configuration read from: C:\GIT\GWM_B037_IC\GWM_B037_MCU\B037_CLIENT_MCU_CFG\OSEK_GEN_F1K\ATB3_L2.oil */
/* generation at  : Sat Jun 15 17:12:11 2019 */
/* Unlimited license CBD1400367 for Magneti Marelli S.p.A., Project License, ATB legal for PSA */
/* Implementation: RenesasRH850_F1L */
/* Version of general code: 5.26 */
/* Dcf-file semantic version: 1.07 */
/* Dcf-file content version: 1.01 */
#ifndef  free_rtos_def_task
#define  free_rtos_def_task

extern void fun1(void);
#define ActivateTask(x)   (fun1())
#define SetEvent(x, y)    (fun1())
#define GetEvent(x, y)    (fun1())
#define ClearEvent(x)     (fun1())
#define WaitEvent(x)      (fun1())

#define SetRelAlarm(x, y, z)  (fun1())
#define CancelAlarm(x)        (fun1())
#define SendMessage(x, y)     (fun1())
#define osSaveDisableLevel()  (fun1())

typedef unsigned short  TaskType;
//typedef unsigned char StatusType;
//#define E_OK 0

typedef enum
{
  EVENT_Task_num,                //EVENT_Task_ts     0)
  IMC_DLA_Task_num,              //IMC_DLA_Task      1)
  IMC_TLA_Task_num,              //IMC_TLA_Task      2)
  NETC_Task_num,                 //NETC_Task_ts      3)
  NETM_Task_num,                 //NETM_Task_ts      4)
  EEPC_Task_num,                 //EEPC_Task_ts      5)
  EEPM_Task_num,                 //EEPM_Task_ts      6)
  TIMC_Task_num,                 //TIMC_Task_ts      7)
  INAC_Task_num,                 //INAC_Task_ts      8)
  RTCC_Task_num,                 //RTCC_Task_ts      9)
  IODC_Task_num,                 //IODC_Task_ts      10)
  DFIN_Task_num,                 //DFIN_Task_ts      11)
  DIMP_Task_num,                 //DIMP_Task_ts      12)
  SNDP_Task_num,                 //SNDP_Task_ts      13)
  WKMM_Task_num,                 //WKMM_Task_ts      14)
  DIMM_Task_num,                 //DIMM_Task_ts      15)
  SDFM_Task_num,                 //SDFM_Task_ts      16)
  APSM_Task_num,                 //APSM_Task_ts      17)
  GPMM_Task_num,                 //GPMM_Task_ts      18)
  WKSS_Task_num,                 //WKSS_Task_ts      19)
  SSCS_Task_num,                 //SSCS_Task_ts      20)
  EOLS_Task_num,                 //EOLS_Task_ts      21)
  LINP_Task_num,                 //LINP_Task_ts      22)
  BATM_Task_num,                 //BATM_Task_ts      23)
  SWCM_Task_num,                 //SWCM_Task_ts      24)
  SAFM_Task_num,                 //SAFM_Task_ts      25)
  DLTM_Task_num,                 //DLTM_Task_ts      26)
  DEVM_Task_num,                 //DEVM_Task_ts      27)
  MAX_Task_num
}FreeRTOS_TaskNumble_t;

/* task start functions (only for call tree) */
extern void INAC_Task_tsfunc(void);

void SAFM_Task_tsfunc(void);
void IMC_DLA_Taskfunc(void);
void IMC_TLA_Taskfunc(void);
void NETC_Task_tsfunc(void);
void NETM_Task_tsfunc(void);
void LINP_Task_tsfunc(void);
void EEPC_Task_tsfunc(void);
void EEPM_Task_tsfunc(void);
void TIMC_Task_tsfunc(void);

void RTCC_Task_tsfunc(void);
//void IODC_Task_tsfunc(void);
void DFIN_Task_tsfunc(void);
void DIMP_Task_tsfunc(void);
void SNDP_Task_tsfunc(void);
void WKMM_Task_tsfunc(void);
void DIMM_Task_tsfunc(void);
void SDFM_Task_tsfunc(void);
void APSM_Task_tsfunc(void);
void GPMM_Task_tsfunc(void);
void BATM_Task_tsfunc(void);
void SWCM_Task_tsfunc(void);
void WKSS_Task_tsfunc(void);
void SSCS_Task_tsfunc(void);
void EOLS_Task_tsfunc(void);
void IDLE_Task_tsfunc(void);

/* Tasks */
#define IMC_DLA_Task ((TaskType)0)
#define SWCM_Task_ts ((TaskType)1)
#define SAFM_Task_ts ((TaskType)2)
#define IMC_TLA_Task ((TaskType)3)
#define NETC_Task_ts ((TaskType)4)
#define NETM_Task_ts ((TaskType)5)
#define LINP_Task_ts ((TaskType)6)
#define EEPC_Task_ts ((TaskType)7)
#define EEPM_Task_ts ((TaskType)8)
#define TIMC_Task_ts ((TaskType)9)
#define INAC_Task_ts ((TaskType)10)
#define RTCC_Task_ts ((TaskType)11)
#define IODC_Task_ts ((TaskType)12)
#define DFIN_Task_ts ((TaskType)13)
#define DIMP_Task_ts ((TaskType)14)
#define SNDP_Task_ts ((TaskType)15)
#define WKMM_Task_ts ((TaskType)16)
#define DIMM_Task_ts ((TaskType)17)
#define SDFM_Task_ts ((TaskType)18)
#define APSM_Task_ts ((TaskType)19)
#define GPMM_Task_ts ((TaskType)20)
#define BATM_Task_ts ((TaskType)21)
#define WKSS_Task_ts ((TaskType)22)
#define SSCS_Task_ts ((TaskType)23)
#define EOLS_Task_ts ((TaskType)24)
#define IDLE_Task_ts ((TaskType)25)

/* Events */

typedef unsigned long EventMaskType;
#define EV_IMC_CYCLIC         ((EventMaskType)(0x01))/* AUTO */
#define EV_IMC_ISR_A_ENDED    ((EventMaskType)(0x02))/* AUTO */
#define EV_IMC_ISR_A_TIMEOUT  ((EventMaskType)(0x04))/* AUTO */
#define EV_IMC_SLAVE_READY    ((EventMaskType)(0x08))/* AUTO */
#define SWCM_10MS_Task_Ev     ((EventMaskType)(0x10))/* AUTO */
#define SWCM_20MS_Task_Ev     ((EventMaskType)(0x20))/* AUTO */
#define SWCM_100MS_Task_Ev    ((EventMaskType)(0x40))/* AUTO */
#define SWCM_50MS_Task_Ev     ((EventMaskType)(0x80))/* AUTO */

#define osdNumberOfAllTasks    MAX_Task_num
#define RTOS_NUMBER_OF_TASK    MAX_Task_num
#define osActiveTaskIndex      MAX_Task_num
#endif

/* END OF C:\GIT\GWM_B037_IC\GWM_B037_MCU\B037_CLIENT_MCU_CFG\OSEK_GEN_F1K\tcb\tcb.h */

