/* Msg(7:0777) [U] External identifier does not differ from other identifier(s) within the specified number 
of significant characters. The function name generated by the Vector tool, so ignore QAC analysis. 
Evaluate: The function name generated by the WdfGen tool, so ignore QAC analysis */ 
/*PRQA S 0777 ++*/ 

/* Msg(7:0779) [U] Identifier does not differ from other identifier(s) within the specified number of significant characters.
Evaluate: The function name generated by the WdfGen tool, so ignore QAC analysis*/
/*PRQA S 0779 ++*/
/******************************************************************************/
/*!
* \file        vers_dynamic.h
* \brief       Dynamic generate header file for vers' types and accesser
* \author      Ken XU
* \since       
* \version     0.1
* \copyright   Magneti Marelli - Guangzhou
*
* \note        This file is generated dynamically, please don't edit!!!
*
* <br>
*/
/******************************************************************************/
#ifndef VERS_DYNAMIC_H
#define VERS_DYNAMIC_H

/* _____ I N C L U D E - F I L E S ___________________________________________*/
#include "Platform_Types.h"

/* _____ G L O B A L - D E F I N E - D E C L A R A T I O N S _________________*/

/* _____ G L O B A L - T Y P E S - D E C L A R A T I O N S ___________________*/
/******************************************************************************/
/*!
* \file        vers_userdef.h
* \brief       Dynamic generate source file
* \author      Magneti
* \since       2020/06/18
* \version     0.1
* \copyright   Magneti Marelli - Guangzhou
*/
/******************************************************************************/

typedef struct
{
  union
  {
    uint8 Byte;
    struct
    {
      uint8 BodyLocked       : 1;   /* bit0   security data access block                       */
      uint8 SysConfProgD     : 1;   /* bit1   system configuration FLORENCE programmed (Proxi) */
      uint8 RemoteData1ProgD : 1;   /* bit2   remote data programmed (table 1)                 */
      uint8 RemoteData2ProgD : 1;   /* bit3   remote data programmed (table 2)                 */
      uint8 ImmoDataProgD    : 1;   /* bit4   immobilizer data programmed                      */
      uint8 Spare            : 3;   /* bit5-7 spare                                            */
    } Bit;
  } Ctrl;
  uint8  Spare1[3];                     /* #Rma For alignment at word */
  uint16 Version;
  uint16 Checksum;
} VERS_ProgStat_t;

typedef struct
{
  uint8  SoftStopFunction : 1 ;     
  uint8  Reserved1  : 7 ;   
  uint8  WindowTemperatureIncrease ;     
  uint8  WindowTemperatureDecrease ;   
  uint8  WindowBlockTemperatureIncrease;
  uint16 WindowThermalProtectionLevel1 ;
  uint16 WindowThermalProtectionLevel2 ;
  uint16 WindowThermalNormalLevel1 ;
  uint16 WindowThermalNormalLevel2 ;
  uint8  UninitializeManualUpPause : 4 ;     
  uint8  RippleBlockDetectTime  : 4 ;  
  uint8  Reserved2 ;  
   
  uint16  CheckSum;
} VERS_WindowCfg_t;


/* MirrorConfiguration : 1701 / 1721 */
typedef struct
{
  uint8  MirrorPositionBlockThreshold : 4 ;     
  uint8  MirrorPositionDeviation  : 4 ;
  uint8  MaxBlockRetryCounter : 4 ;   
  uint8  BlindDetectSet : 1 ;   
  uint8  Reserved1  : 3 ;  
  uint8  Reserved2[10] ;
  uint16  CheckSum;
} VERS_MirrorCfg_t;


/* HandleConfiguration : 1702 / 1722 / 1742 / 1762 */
typedef struct
{
  uint8  ExtractRetractMaxAction : 4 ;     
  uint8  ExtractRetractCutoffDelay : 3 ;
  uint8  SignalsHandlePosition : 1 ;
  uint8  DoorHandleNormalInhibit ;     
  uint8  DoorHandleAbnormalInhibit;  
//  uint8  TDoorHandleCmdInhibit ;
//  uint8  TWDoorHandContinuous ;
  uint16  LastReprogrammingCounter;
  uint16  HallTurn;
  uint8  InitializedFlag;
  uint8  DoorHndlSts;
  uint8  NormalSleepFlag ;
  uint16  CheckSum;
} VERS_HandleCfg_t;


/* VoltageModeConfiguration : 1704 / 1724 / 1744 / 1764 */
/* PowerModeConfiguration   : 1705 / 1725 / 1745 / 1765 */
typedef struct
{
  uint8  VolModeConfirmTime; 
  uint8  Reserved1 ;
  uint8  GoToSleepTime;
  uint8  VFCInfoEna  ;
  uint8  Spaced[10] ;
  uint16  CheckSum;
} VERS_VolPowerModeCfg_t;

/* DID  : 4058 / 4059 / 405A / 405B */
/* DID  : 419A / 419D / 419E / 419F  */
typedef struct
{
  uint8  LCMA_WarningLevel_1_Night; 
  uint8  LCMA_WarningLevel_2_Night;
  uint8  LCMA_WarningLevel_1_Day;
  uint8  LCMA_WarningLevel_2_Day;
  
  uint16  LCMA_Min_WarningLevel_1; 
  uint16  LCMA_Min_WarningLevel_2;
  uint16  LCMA_WarningLevel_2_OFF;
  uint16  LCMA_WarningLevel_2_ON;

  uint16  Reserved;
  uint16  CheckSum;
} VERS_LCMAModuleCfg_t;


/* DTC Control Bit Configuration   : 1706 / 1726 / 1746 / 1766 */
typedef struct
{
  uint8  BitData[10]; 
  uint8  Reserved[4];
   
  uint16  CheckSum;
} VERS_DTCcontrolBitCfg_t;




/* Mirror memory position structure for 170B / 172B / 174B / 176B */
typedef struct
{
  uint16 NormalPos_X;
  uint16 NormalPos_Y;
  uint16 ReversePos_X;
  uint16 ReversePos_Y;
} VERS_MemPos_t;

  
/* Read Mirror memory position   : 170B / 172B / 174B / 176B */
typedef struct
{
  VERS_MemPos_t MemPos[10];
  uint8  Reserved[6];
  uint16 Checksum;
} VERS_MemPosUsrID_t;

typedef struct
{
  uint16 NormalPos_X;
  uint16 NormalPos_Y;
  uint16 TiltDwnPos_X;
  uint16 TiltDwnPos_Y;  
  
} VERS_MemPos_Bank_t;

typedef struct
{
  VERS_MemPos_Bank_t MemBank1[13];
  VERS_MemPos_Bank_t MemBank2[13];
  VERS_MemPos_Bank_t MemBank3[13];
  uint8 AutoFoldCfgDrvr[13];
  uint8 AutoFoldCfgPass[13];
  uint8 AutoDipCfgDrvr[13];
  uint8 AutoDipCfgPass[13];
  uint8 Reserved[10];
  uint16 Checksum;
}VERS_SR_PROFILE_t;

typedef struct {
  uint8  LockgCenSts;
  uint8  MirrDwnStsAtDrvr;
  uint8  MirrDwnStsAtPass; 
  uint8  reserved[3];
  uint16  Checksum;         /* Checksum */
} VERS_Other_1;

typedef struct
{
  VERS_MemPos_Bank_t MemPosMask;
  uint8 reserve[10];
  uint16 Checksum;
} VERS_MIRR_POS_REC_t;

typedef struct
{
  uint8 EEP_FoldSts;
  uint8 EEP_TiltSts;
  uint8 EEP_MirrorHeatingAction;
  uint8 EEP_MaxMirrorAdjustTime;
  uint8 EEP_MaxBlockRetryCounter;
  uint8 EEP_DynamicMirrorSts:1;
  uint8 EEP_ManualFold:1;
  uint8 Reserved1:6;
  uint16 UntiltPosX;
  uint16 UntiltPosY;
  uint16 SearchPosX;
  uint16 SearchPosY;
  uint16 FoldPeak;
  uint8  Reserved[5];
  uint16 Checksum;
} VERS_MirrorSt_t;




/** DTC data structure */
typedef union
{
  uint8 Byte;
  struct
  {                     
   /* Architettuta NXP S32 */
   uint8 testFailed                           :1;   /* Bit0 */
   uint8 testFailedThisMonitoringCycle        :1;   /* Bit1 */
   uint8 pendingDTC                           :1;   /* Bit2 */
   uint8 confirmedDTC                         :1;   /* Bit3 */
   uint8 testNotCompletedSinceLastClear       :1;   /* Bit4 */
   uint8 testFailedSinceLastClear             :1;   /* Bit5 */
   uint8 testNotCompletedThisMonitoringCycle  :1;   /* Bit6 */
   uint8 warningIndicatorRequest              :1;   /* Bit7 */
  }Bit;
}VERS_DtcStatus_t;


/*One DTC should include total 44 bytes  */
typedef struct VERS_DtcBlock_s
{
  VERS_DtcStatus_t          Status;        /* DTC status         */

  /* $19 06 DTC Extend Data : 17 bytes*/
  uint8         OCC_1;   /* Operation cycle counter #1   */
  uint8         OCC_2;   /* Operation cycle counter #2   */
  uint8         OCC_3;   /* Operation cycle counter #3   */
  uint8         OCC_4;   /* Operation cycle counter #4   */
  uint8         OCC_6;   /* Operation cycle counter #6   */
  uint8         FDC_10;  /* Fault Detection Counter#10   */
  uint8         FDC_11;  /* Fault Detection Counter#11   */
  uint8         FDC_12;  /* Fault Detection Counter#12   */
  uint32        TimeStamp_20;  /* DTC Time Stamp 20 */
  uint32        TimeStamp_21;  /* DTC Time Stamp 21 */
  uint8         Status_Indicator_30;  /* DTC Status indicator 30 */ 
   
  /* $19 04 DTC SnapShot Data  : 24 bytes */
  /* SnapShot Record NO 20 definition  : 24 bytes */
  uint16        SupplyVoltage_20;   /* 22 D1 10 */
  uint32        GlobalRealTime_20;  /* 22 DD 00 */
  uint32        TotalDistance_20;   /* 22 DD 01 */  /* Actually use 3 bytes */
  uint8         BatteryVoltage_20;  /* 22 DD 02 */
  uint8         OutsideTemp_20;     /* 22 DD 05 */
  uint8         UsageMode_20;       /* 22 DD 0A */
  uint8         E_PowerLevel_20;    /* 22 DD 0C */  
  uint8         DoorHandleState_20;         /* 22 45 9E */
  uint8         Switches_Status_20;         /* 22 40 F4 */ 
  /*2000/2001/2100/2101*/
  uint8         UTCTime[5];         /* 22 90 07 */
  uint8         CarMode;         /* 22 D1 34*/
  uint8         Reserved[3];
}VERS_DtcBlock_t; 

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK1_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK2_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK3_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK4_t;

/* One block is total 348 bytes */
typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK5_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK6_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK7_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK8_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK9_t;

typedef struct
{
  /* VERS_DtcBlock_t is total 44 bytes */
  VERS_DtcBlock_t  DTCBuf[14];

  uint8  Reserved[6];

  /* checksum */
  uint16 checksum;
  
} VERS_DTC_DATA_BLOCK10_t;


#define VERS_NM_ST_HIS_NUM  10
#define VERS_NM_ST_HIS_SZ   5

/* Wakeup Source Storage structure  */
typedef struct
{
  uint8  EEP_GoToSleepTime;
  uint8  EEP_BCM_ATWS_ST;
  uint8  EEP_WAKEUP_SRC_1;
  uint8  EEP_WAKEUP_SRC_2;
  uint8  EEP_WAKEUP_SRC_3;
  uint8  EEP_WAKEUP_SRC_4;
  uint8  EEP_WAKEUP_SRC_5;
  uint8  EEP_WAKEUP_SRC_6;
  uint8  EEP_WAKEUP_SRC_7;
  uint8  EEP_WAKEUP_SRC_8;
  uint8  EEP_WAKEUP_SRC_9;
  uint8  EEP_WAKEUP_SRC_10;  
  uint8  NmHisBuf[VERS_NM_ST_HIS_NUM][VERS_NM_ST_HIS_SZ];
  uint16 NmHisBufIdx;
  uint8  Reserved[10];
  uint16  CheckSum;
} VERS_PMM_t; 
 
/* Vehicle Configuration Struct */
typedef struct
{
  uint8  HighQ_CurrFuncSts; /* High quiescent current function status */
  
  uint8  Reserved[5];
  uint16  CheckSum;
} VERS_VehCfg_t; 

typedef struct {
  uint16 CcpIdx;
  uint8 Value;
} VERS_CarCfgPara_t;

typedef struct {
  VERS_CarCfgPara_t Para[10];
  uint16 TotalNum;
} VERS_CarCfgFaulty_t;

typedef struct {
  uint8   Para[96];
  uint16  MagicNum;
} VERS_CarCfg_t;

typedef struct {
  VERS_CarCfg_t CarCfg;
  VERS_CarCfgFaulty_t CarCfgFault;
  uint16  CheckSum;
}VERS_CCP_t;

/* Anti-Pinch Learning */
typedef struct
{
  uint8 ApprenticeTable_ini;
  uint8 Torque_HighThreshold;
  uint8 Torque_LowThreshold;
  uint8 TorqueHard_HighThld;
  uint8 TorqueHard_LowThld;
  uint8 Torque_Ignore;
  /* Section regarding WLCARTO */
  sint8 WLCarto[2][500];        /*Corresponding to POSA_MAX_POSITION_RANGE, the maximum is 500 * 12*/
  uint16 VentUpStopCorrVal[4];  /*ventilated up stop Corrected vaule*/
  uint16 VentDownStopCorrVal[4];/*ventilated down stop Corrected vaule*/
  uint8  Reserve[10];
}VERS_APLearn_t;

typedef struct
{
 uint16 EEP_MotorThermalPro_T1;
 uint16 EEP_MotorThermalPro_T2;
 uint8  EEP_LeftChildLockSts;
 uint8  EEP_RightChildLockSts;
 uint8  ShrtDrpFlg;
 uint8  ShortDropWinSts;
 uint8  WL_GlbDelayTime[4];

 uint8  WL_ManualSpeedUp;
 uint8  WL_ManualSpeedDown;
 uint8  WL_AutoSpeedUp;
 uint8  WL_AutoSpeedDown;

 uint8  WL_ManualAcclFromStop;
 uint8  WL_AutoAcclFromStop;
 uint8  WL_AcclManualToAuto;
 uint8  WL_ManualDecelFromStop;
 uint8  WL_AutoDecelFromStop;
 uint8  WL_DecelAutoToManual;

 uint8  WL_MaxVehSpeedFromOpen;
 uint8  WL_PowerSoftstop;
 uint8  WL_PowerPinchProtec;
 uint8  WL_PowerThermoProtec;
 uint8  WL_CycReinPeriodSoftstop[8];

 uint8  WL_AccelStopSmokAuto; /*45D8*/
 uint8  WL_AccelFromSmokManu;/*45D9*/
 uint8  WL_DecelFromSmokToStop;/*45DB*/
 uint8  WL_DecelFromManuToSmok;/*45DD*/
 uint8  WL_FacFailReson;
 uint8  WL_DoorSts;
 uint16 WL_AntiPinchCnt;
 uint16 WL_BlockCnt;
 uint16 WL_Res;
 uint8  Reserve[10];
} VERS_WLC_t;

typedef struct
{
  VERS_WLC_t  WLC;
  VERS_APLearn_t APLearn;
  uint16  CheckSum;
} VERS_WLC_APLearn_t;

typedef struct
{
  uint8     StdAPCriterionThreshold10[2];
  uint8     StdAPCriterionThreshold12[2];
  uint8     StdAPCriterionThreshold14[2];
  uint8     StdAPCriterionThreshold16[2];
  uint8     TOR_BIAS;
  uint8     WayToApprenticeTable;
  uint8     WayToDegradationCriterion;
  uint8     MaxGap;
  uint8     WayToDegradationCriterionBBM;
  uint8     WidthOfWayToCalculateCriterion;
  uint8     TimeForMaxDetec;
  uint8     BlockTimeOut;
  uint8     WayToDegradationBelow;
  uint8     ThresholdForBellowParam;  /*0.093 volt/lsb*/
  sint8     Hard_CriterionThreshold;
  uint16    MaxForMaxDetec;
  uint16    MinForMaxDetec;
  uint16    Version;
  uint8     Reserved[4];
}VERS_APFilter_t;

/* Anti-Pinch Hardening */
typedef struct
{
  uint8   BCstFilter;
  uint8   BCstFilterBelow;
  uint8   BwThreshold1;
  uint8   BwThreshold2;
  uint8   BwThreshold3;
  uint8   BwVApCriterionOffset1;
  uint8   BwVApCriterionOffset2;
  uint8   BwVApCriterionOffset3;
  uint8   BwVTiming1;
  uint8   BwVTiming2;
  uint8   BwVTiming3;
  uint8   k_BwV;
  uint8   VoltFlucThreshold1;
  uint8   VoltFlucThreshold2;
  uint8   VoltFlucThreshold3;
  uint8   Neg_Threshold_timing;
  uint16  Version;
  uint8   Reserved[4];
}VERS_APHardening_t;

/* Anti-Pinch Seal */
typedef struct
{
  uint8   FstSealAPCriterionOffest;
  uint8   FstWaySealDetec;
  uint8   SndSealAPCriterionOffest;
  uint8   SndWaySealDetec;
  uint16  APArea_LowThld[2];
  uint16  SealPosition_ref;
  uint8   SealPosition_HighThreshold;
  uint8   SealPosition_LowThreshold;
  uint8   SealUpdateProcedure;
  uint8   StdSealThreshold;
  uint8   reserved[4];
  uint16  Version;          /* Version  */
}VERS_APSeal_t;

/* Anti-Pinch Coding */
typedef struct
{
  uint8 MechHighEdgeHighThreshold;
  uint8 MechHighEdgeLowThreshold;
  uint16 MaxWdwLgth;
  uint8 MechLowEdgeThreshold;
  uint8 ThresholdBetweenMechAndSWLowEdge;
  uint8 NumOfCycleOfLowSoftStop;
  uint8 ReversalDist;
  uint8 DeltaWdwLgth;
  uint8 SoftStpRelativePosit;
  uint8 LowSoftStopConst;
  uint8 HighSoftStopConst;
  uint8 KineticCalcCst;
  uint8 CmdAuthoriDelay;
  uint8 StaticCurrGrad;
  uint8   reserved[4];
} VERS_APStopConfig_t;

/* Anti-Pinch Para */
typedef struct
{
  VERS_APFilter_t APFilter;
  VERS_APHardening_t APHardening;
  VERS_APSeal_t APSeal;
  VERS_APStopConfig_t APStopConfig;
  uint16  CheckSum;
}VERS_AP_Para_t;

typedef struct
{
  uint8   NeverBeenInitialized_Cur[2];
  uint8   R1_ExceedTimes_Cur[2];
  uint8   R2_PowerOff_Cur[2];
  uint8   R3_PosError_Cur[2];
  uint8   R4_APOverride_Cur[2];
  uint8   R5_Other1_Cur[2];
  uint8   R6_Other2_Cur[2];
  uint8   SoftStopCounter_Cur[2];
  uint8   NeverBeenInitialized_Last[2];
  uint8   R1_ExceedTimes_Last[2];
  uint8   R2_PowerOff_Last[2];
  uint8   R3_PosError_Last[2];
  uint8   R4_APOverride_Last[2];
  uint8   R5_Other1_Last[2];
  uint8   R6_Other2_Last[2];
  uint8   SoftStopCounter_Last[2];
  uint8   Reserve[10];
} VERS_WL_INIT_INFOR_t;

typedef struct
{
  uint8  reserve;
  uint8  cmdAction[15];             /*bit4-7 cmd action, bit0-3 cmd Src*/
  uint8  voltage[15];               /*voltage*/
  uint8  keySts[15];                /*key status*/
  uint8  backEMFCnt[15];            /*BEMF for each action*/
  uint8  maxPeriodRpctCnt[15];      /*Ripple Cnt with period exceeding Rpct_Max_period*/  
  uint8  delayPeakDetected[15];     /*Waiting time for finding ripple peaks or troughs*/
  uint8  runningTime[15];           /*running time(unit 50ms)*/
  uint16 startPosition[15];         /*startPosition*/
  uint16 endPosition[15];           /*endPosition*/
  uint16 BJTimeDateHour[15];        /*bit8-15  data,   bit0-7  hour   */ 
  uint16 BJTimeMintSec[15];         /*bit8-15  minute, bit0-7  second */  
  uint16 powerOnTime;               /*bit8-15  data,   bit0-7  hour   */ 
  uint8  operateIdx;                /*bit8-15  data,   bit0-7  hour   */
  uint8  Spared[10];
} VERS_WLAPLogDym_t;

typedef struct
{
  uint8  reserve;
  uint8  cmdAction[15];             /*bit4-7 cmd action, bit0-3 cmd Src*/
  uint8  voltage[15];               /*voltage*/
  uint8  keySts[15];                /*key status*/
  uint8  backEMFCnt[15];            /*BEMF for each action*/
  uint8  maxPeriodRpctCnt[15];      /*Ripple Cnt with period exceeding Rpct_Max_period*/
  uint8  delayPeakDetected[15];     /*Waiting time for finding ripple peaks or troughs*/
  uint8  runningTime[15];           /*running time(unit 50ms)*/
  uint16 startPosition[15];         /*startPosition*/
  uint16 endPosition[15];           /*endPosition*/
  uint16 BJTimeDateHour[15];        /*bit8-15  data,   bit0-7  hour   */
  uint16 BJTimeMintSec[15];         /*bit8-15  minute, bit0-7  second */
  uint16 powerOnTime;               /*bit8-15  data,   bit0-7  hour   */
  uint8  operateIdx;                /*bit8-15  data,   bit0-7  hour   */
  uint8  Spared[10];
} VERS_WLAPLogSta_t;

typedef struct
{
  VERS_WL_INIT_INFOR_t WL_InitInfo;
  VERS_WLAPLogDym_t WLAPLogDym;
  VERS_WLAPLogSta_t WLAPLogSta;
  uint16 CheckSum;
} VERS_WL_Log_t;

typedef struct
{
  uint8 SBCErrorCounter;
  uint8 NetWorkWakeupErrorCounter;
  uint8 SpiCommunicationErrorCounter;
  uint8 PncEnableErrorCounter;
  uint32 SBCControlRegisterCR1;
  uint32 SBCControlRegisterCR2;
  uint32 SBCControlRegisterCR3;
  uint32 SBCControlRegisterCR4;
  uint32 SBCControlRegisterCR5;
  uint32 SBCControlRegisterCR6;
  uint32 SBCControlRegisterCR7;
  uint32 SBCControlRegisterCR8;
  uint32 SBCControlRegisterCR9;
  uint32 SBCControlRegisterCR10;
  uint32 SBCControlRegisterCR11;
  uint32 SBCControlRegisterCR12;
  uint32 SBCControlRegisterCR13;
  uint32 SBCControlRegisterCR14;
  uint32 SBCControlRegisterCR15;
  uint32 SBCControlRegisterCR16;
  uint32 SBCControlRegisterCR17;
  uint32 SBCControlRegisterCR18;
  uint32 SBCControlRegisterCR19;
  uint32 SBCControlRegisterCR20;
  uint32 SBCControlRegisterCR21;
  uint32 SBCControlRegisterCR22;
  uint32 SBCControlRegisterCR23;
  uint32 SBCControlRegisterCR24;
  uint32 SBCControlRegisterCR25;
  uint32 SBCControlRegisterCR26;
  uint32 SBCControlRegisterCR27;
  uint32 SBCControlRegisterCR28;
  uint32 SBCControlRegisterCR29;
  uint32 SBCControlRegisterCR34;
  uint32 SBCConfigurationRegister;
  uint32 SBCStatusRegisterSR1;
  uint32 SBCStatusRegisterSR2;
  uint32 SBCStatusRegisterSR3;
  uint32 SBCStatusRegisterSR4;
  uint32 SBCStatusRegisterSR5;
  uint32 SBCStatusRegisterSR6;
  uint32 SBCStatusRegisterSR7;
  uint32 SBCStatusRegisterSR8;
  uint32 SBCStatusRegisterSR9;
  uint32 SBCStatusRegisterSR10;
  uint32 SBCStatusRegisterSR11;
  uint32 SBCStatusRegisterSR12;
} VERS_DebugData_t;

/* Window lift Context for Anti-Pinch*/
typedef struct
{
  /* Section regarding WLCONTEXT */
  uint16  MotorPosition[2];
  uint16  LowSoftStopPosition[2];
  uint8   WdwInitState[2];
  uint8   PEPSHighBlockCounter[2];
  uint8   LowSoftStopCnter[2];
  uint8   HighSoftStopCnter[2];
  uint8   WindowActivCnter[2];
  uint16  SealPosition[2];
  uint8   LastStopPosition[2];
  uint8   PositionStop[2];
  uint8   LastKeyState;
  uint8   WLBlocking[2];
  uint8   Lowblockfinnish[2];
  uint8   Spare[10];
  /* Section regarding version and chksum */
  uint16  Version;
  uint16  Checksum;
} VERS_WLContext_t ;

/* Window lift Context for Anti-Pinch*/
typedef struct
{
  uint16  LastKeyState;
  uint8   SaveAsUnInit;              /*Used as a record, normal out of range initialization*/
  uint8   SaveErrorTime;             /*Used as a record, due to multiple ripple loss initialization*/
  uint16  InitSateSaveTime;
  uint16  MotorZeroPosition;
  uint16  MotorSavePosition;
  uint16  MotorOutFramePosition;
  uint16  Error3Position;
  uint16  WINMaxPosition[2];        /*Used as a record, lower mechanical point position*/
  uint16  LastReprogrammingCounter;
  uint8  Reserve[10];
} VERS_WLLOG_t;

/*Struct VERS_WL_MC_DrvConf_t*/
typedef struct
{
  /* Parameters for PWM Driving */
  uint8  PWMCtrlEnable;      /* Enable the PWM driving */
  uint8  PWMBattComp;        /* 0 - Battery compensation disabled, 1 - Battery compensation enabled only at the start of mvt, 2 - Continuos battery compensation during mvt */
  uint16 PWMDutyVal;         /* In case of compensation disabled, specify a fixed value for the duty cycle */

  /* Parameters for "stop before mechanical low block" functionality */
  uint8  AdjLowBlockStopEnable; /* Enable the stop before low mechanical block (adjustable) */

  /* Parameters for Soft Start driving */
  uint8  SStartEnable;      /* Enable soft start */
  uint16 SStartDutyVal;     /* Duty cycle starting value */
  uint16 SStartIncStep;     /* Increment expressed in % of duty cycle */
  uint8  SStartIncDly;      /* Time interval used to apply the increment of the ramp (SStartIncStep) */

  /* Parameters for Soft Stop driving */
  uint8  SStopEnable;       /* Enable soft stop */
  uint16 SStopDutyVal;      /* Duty cycle arrival value */
  uint16 SStopDecStep;      /* Increment expressed in % of duty cycle */
  uint8  SStopDecDly;       /* Time interval used to apply the increment of the ramp (SStartIncStep) */
  uint8  Spare[1];          /* Spare byte */
  uint16 SStopStartPos;     /* Window position in which start the soft stop procedure */

  uint16 Version;           /* Version  */
} VERS_WL_MC_DrvConf_t;

/* Window lift Info */
typedef struct
{
  VERS_WLContext_t WLContext;
  VERS_WLLOG_t WLLog;
  VERS_WL_MC_DrvConf_t WL_MC_DrvConf;
  uint16 Checksum;
}VERS_WL_INFO_t;

/*window lift ProdConfig*/
typedef struct {
  uint8   DoorMotorPolarity;  
  uint8   TimeMechanicalEdge;  
  uint8   MaxNbrWithoutBlocking;
  uint8   TrialAmountWihtAPEnable;
  uint16  Version;
  uint16  Checksum;
} VERS_WL_ProdConfig_t;

typedef struct {
  uint8   HighMechanicalEdge_HighThreshold;
  uint8   HighMechanicalEdge_LowThreshold;
  uint8   LowSoftStopConst; 
  uint8   KineticCalcCst;
  uint8   CmdAuthoriDelay;
  uint8   MotorBrakCst;
  uint8   StaticCurrGrad;
  uint8   Spare;
  uint16  ReversalDist;
  uint16  MaxWdwLgth[2];
  uint16  DeltaWdwLgth;
  uint16  SoftStpRelativePosit[2];
  uint16  Version;          /* Version  */
  uint8  Reserve[10];
  uint16  Checksum;         /* Checksum */
} VERS_APConnex_t;

typedef struct {
  uint16  ThermProtCnt[2];            /* Thermal protection counter*/
  uint8   ThermProtState[2];          /* Thermal protection state*/
  uint8   NumOfUpActions[2];          /* Number of close actions in current protection cycle*/
  uint8   NumOfDownActions[2];
  uint8   ThermProtEnable;
  
  uint8  AutoLearnCnt;/*45DF*/
  uint8  WL_ShortDropTime; /*D939*/
  uint8   PartialNetworkCluster[2]; /*DID:DD0B*/
  uint8   RoutineSelftestFailureReason[2]; /*DID:FD40*/
  uint16  WL_Pinch;/*D928*/
  uint16  Close50Cnt;/*D950*/
  uint16  WL_ShortDropDist;/*D951*/
  uint16  WL_SmokGapUpperPosit;/*D952*/
  uint16  WL_SmokGapLowerPosit;/*D953*/
  uint16  AutoLearnThreshold;
  uint8   Reserved[10];
  uint16  CheckSum;
} VERS_THPA_t;

typedef struct
{
 uint8 ChdPrtnLeftFailStsToHmi;
 uint8 ChdLockRightFailStsToHmi;
 uint8 ChdPrtnLeftStsToHmi;
 uint8 ChdLockRightStsToHmi;
 uint8 ChdPrtnLeftLedReq;
 uint8 ChdPrtnRightLedReq;
 uint8 ChdLockLeftCmdFlag;
 uint8 ChdLockRightCmdFlag;
 uint8 WinDsblLeftCmd;
 uint8 WinDsblRightCmd;
 uint8 CentralLockStatus;
 uint8 DoubleLockStatus;
 uint8 ChildLockStatus;
 uint8 LockSwStatusLed;
 uint8 DoorLockSts;
 uint8 ChdLockSts;
 uint8 DoorDrvrLockCmdFlag;
 uint8 CrashUnlockFlag;
 uint8 CanLockBusy;
 uint8 ResetBitFailFlag;
 uint8 LatchPosition; 
 uint16 HBridgeShuntOffsetAd;
 uint8 Reserve[10];
 uint16 CheckSum;
} VERS_DLC_t;



/* QCM Faults record */
typedef struct
{ 
  uint32 QCM_SGT;           /* System Global Time */ 
  uint32 QCM_EWGT;          /* Last Ecu wakeup Time */
  uint8 QCM_ActCondiction;
  uint8 QCM_VFCVector;
  uint8 QCM_CurTypesOfAct;
  uint8 QCM_UsgMode;
  uint8 QCM_WakeUpPnc0;
  uint8 QCM_WakeUpPnc1;
  uint8 QCM_WakeUpPnc2;
} VERS_QCM_Fault_t;

#define VERS_QCM_FAULT_SZ               5
typedef struct
{ 
  VERS_QCM_Fault_t  VERS_QCM_Fault[VERS_QCM_FAULT_SZ]; 
  uint8 QCMFaultBufIdx;
  uint8 Reserved; 
  uint16 checksum;  /* checksum */  
} VERS_QCM_FAULT_DATA_t ;

#define VERS_SYS_ERR_MAX  32
#define VERS_SYS_ERR_M1   1
#define VERS_SYS_ERR_M2   2
#define VERS_SYS_ERR_M3   3
#define VERS_SYS_ERR_M4   4
#define VERS_SYS_ERR_M5   5
#define VERS_SYS_ERR_M6   6
#define VERS_SYS_ERR_M7   7
#define VERS_SYS_ERR_M8   8

typedef struct
{
  uint8 Module[VERS_SYS_ERR_MAX];
  uint8 Code[VERS_SYS_ERR_MAX];
  uint32 Para[VERS_SYS_ERR_MAX];
  uint16 Idx;
  uint16  CheckSum;
}VERS_SysErrLog_t;

typedef struct
{
  uint8 Debug_Msg1;
  uint8 Debug_Msg2;
  uint8 Debug_Msg3;
  uint8 Debug_Msg4;
  uint8 Debug_Msg5;
  uint8 Debug_Msg6;
  uint8 Debug_Msg7;
  uint8 Debug_Msg8;
}VERS_Debug_Msg_t;
/* _____ G L O B A L - D A T A - D E F I N I T I O N S _______________________*/

/* _____ G L O B A L - M A C R O S - D E C L A R A T I O N S _________________*/

/* _____ G L O B A L - F U N C T I O N S - P R O T O T Y P E S _______________*/
extern void VERS_SetProgStatBodyLocked(uint8 val);
extern uint8 VERS_GetProgStatBodyLocked(void);

extern void VERS_SetProgStatSysConfProgD(uint8 val);
extern uint8 VERS_GetProgStatSysConfProgD(void);

extern void VERS_SetProgStatRemoteData1ProgD(uint8 val);
extern uint8 VERS_GetProgStatRemoteData1ProgD(void);

extern void VERS_SetProgStatRemoteData2ProgD(uint8 val);
extern uint8 VERS_GetProgStatRemoteData2ProgD(void);

extern void VERS_SetProgStatImmoDataProgD(uint8 val);
extern uint8 VERS_GetProgStatImmoDataProgD(void);

extern void VERS_SetProgStatSpare1(const uint8 *buf, uint16 len);
extern void VERS_SetProgStatSpare1ByIdx(uint16 idx, uint8 val);
extern void VERS_GetProgStatSpare1(uint8 *buf, uint16 len);
extern uint8 *VERS_GetProgStatSpare1Addr(void);
extern uint8 VERS_GetProgStatSpare1ByIdx(uint16 idx);

extern void VERS_SetWindowCfgSoftStopFunction(uint8 val);
extern uint8 VERS_GetWindowCfgSoftStopFunction(void);

extern void VERS_SetWindowCfgWindowTemperatureIncrease(uint8 val);
extern uint8 VERS_GetWindowCfgWindowTemperatureIncrease(void);

extern void VERS_SetWindowCfgWindowTemperatureDecrease(uint8 val);
extern uint8 VERS_GetWindowCfgWindowTemperatureDecrease(void);

extern void VERS_SetWindowCfgWindowBlockTemperatureIncrease(uint8 val);
extern uint8 VERS_GetWindowCfgWindowBlockTemperatureIncrease(void);

extern void VERS_SetWindowCfgWindowThermalProtectionLevel1(uint16 val);
extern uint16 VERS_GetWindowCfgWindowThermalProtectionLevel1(void);

extern void VERS_SetWindowCfgWindowThermalProtectionLevel2(uint16 val);
extern uint16 VERS_GetWindowCfgWindowThermalProtectionLevel2(void);

extern void VERS_SetWindowCfgWindowThermalNormalLevel1(uint16 val);
extern uint16 VERS_GetWindowCfgWindowThermalNormalLevel1(void);

extern void VERS_SetWindowCfgWindowThermalNormalLevel2(uint16 val);
extern uint16 VERS_GetWindowCfgWindowThermalNormalLevel2(void);

extern void VERS_SetWindowCfgUninitializeManualUpPause(uint8 val);
extern uint8 VERS_GetWindowCfgUninitializeManualUpPause(void);

extern void VERS_SetWindowCfgRippleBlockDetectTime(uint8 val);
extern uint8 VERS_GetWindowCfgRippleBlockDetectTime(void);

extern void VERS_SetMirrorCfgMirrorPositionBlockThreshold(uint8 val);
extern uint8 VERS_GetMirrorCfgMirrorPositionBlockThreshold(void);

extern void VERS_SetMirrorCfgMirrorPositionDeviation(uint8 val);
extern uint8 VERS_GetMirrorCfgMirrorPositionDeviation(void);

extern void VERS_SetMirrorCfgMaxBlockRetryCounter(uint8 val);
extern uint8 VERS_GetMirrorCfgMaxBlockRetryCounter(void);

extern void VERS_SetMirrorCfgBlindDetectSet(uint8 val);
extern uint8 VERS_GetMirrorCfgBlindDetectSet(void);

extern void VERS_SetLockUnlockCfgHBridgeShuntOffsetAd(uint16 val);
extern uint16 VERS_GetLockUnlockCfgHBridgeShuntOffsetAd(void);

extern void VERS_SetHandleCfgExtractRetractMaxAction(uint8 val);
extern uint8 VERS_GetHandleCfgExtractRetractMaxAction(void);

extern void VERS_SetHandleCfgExtractRetractCutoffDelay(uint8 val);
extern uint8 VERS_GetHandleCfgExtractRetractCutoffDelay(void);

extern void VERS_SetHandleCfgSignalsHandlePosition(uint8 val);
extern uint8 VERS_GetHandleCfgSignalsHandlePosition(void);

extern void VERS_SetHandleCfgDoorHandleNormalInhibit(uint8 val);
extern uint8 VERS_GetHandleCfgDoorHandleNormalInhibit(void);

extern void VERS_SetHandleCfgDoorHandleAbnormalInhibit(uint8 val);
extern uint8 VERS_GetHandleCfgDoorHandleAbnormalInhibit(void);

//extern void VERS_SetHandleCfgTDoorHandleCmdInhibit(uint8 val);
//extern uint8 VERS_GetHandleCfgTDoorHandleCmdInhibit(void);

//extern void VERS_SetHandleCfgTWDoorHandContinuous(uint8 val);
//extern uint8 VERS_GetHandleCfgTWDoorHandContinuous(void);

extern void VERS_SetHandleCfgHallTurn(uint16 val);
extern uint16 VERS_GetHandleCfgHallTurn(void);

extern void VERS_SetHandleCfgInitializedFlag(uint8 val);
extern uint8 VERS_GetHandleCfgInitializedFlag(void);

extern void VERS_SetHandleCfgDoorHndlSts(uint8 val);
extern uint8 VERS_GetHandleCfgDoorHndlSts(void);

extern void VERS_SetHandleCfgNormalSleepFlag(uint8 val);
extern uint8 VERS_GetHandleCfgNormalSleepFlag(void);

extern void VERS_SetLockUnlockCfgLockUnlockActionTime(uint8 val);
extern uint8 VERS_GetLockUnlockCfgLockUnlockActionTime(void);

extern void VERS_SetLockUnlockCfgChargeLidActionTime(uint8 val);
extern uint8 VERS_GetLockUnlockCfgChargeLidActionTime(void);

extern void VERS_SetLockUnlockCfgLockStatusLED(uint8 val);
extern uint8 VERS_GetLockUnlockCfgLockStatusLED(void);

extern void VERS_SetLockUnlockCfgHWCrashConfirmTime(uint8 val);
extern uint8 VERS_GetLockUnlockCfgHWCrashConfirmTime(void);

extern void VERS_SetLockUnlockCfgDoorLamp(uint8 val);
extern uint8 VERS_GetLockUnlockCfgDoorLamp(void);

extern void VERS_SetLockUnlockCfgDoorLockSts(uint8 val);
extern uint8 VERS_GetLockUnlockCfgDoorLockSts(void);

extern void VERS_SetLockUnlockCfgChildLockSts(uint8 val);
extern uint8 VERS_GetLockUnlockCfgChildLockSts(void);

extern void VERS_SetLockUnlockCfgChildLockHWSts(uint8 val);
extern uint8 VERS_GetLockUnlockCfgChildLockHWSts(void);

extern void VERS_SetLockUnlockCfgLockUnlockAction(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockActionByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockAction(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockActionAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockActionByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockSource(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockSourceByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockSource(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockSourceAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockSourceByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockYear(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockYearByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockYear(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockYearAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockYearByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockMonth(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockMonthByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockMonth(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockMonthAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockMonthByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockDay(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockDayByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockDay(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockDayAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockDayByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockHour(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockHourByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockHour(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockHourAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockHourByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockMin(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockMinByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockMin(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockMinAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockMinByIdx(uint16 idx);

extern void VERS_SetLockUnlockCfgLockUnlockSec(const uint8 *buf, uint16 len);
extern void VERS_SetLockUnlockCfgLockUnlockSecByIdx(uint16 idx, uint8 val);
extern void VERS_GetLockUnlockCfgLockUnlockSec(uint8 *buf, uint16 len);
extern uint8 *VERS_GetLockUnlockCfgLockUnlockSecAddr(void);
extern uint8 VERS_GetLockUnlockCfgLockUnlockSecByIdx(uint16 idx);

extern void VERS_SetVolPowerModeCfgVolModeConfirmTime(uint8 val);
extern uint8 VERS_GetVolPowerModeCfgVolModeConfirmTime(void);

extern void VERS_SetVolPowerModeCfgGoToSleepTime(uint8 val);
extern uint8 VERS_GetVolPowerModeCfgGoToSleepTime(void);

extern void VERS_SetVolPowerModeCfgVFCInfoEna(uint8 val);
extern uint8 VERS_GetVolPowerModeCfgVFCInfoEna(void);

extern void VERS_SetVolPowerModeCfgSpaced(const uint8 *buf, uint16 len);
extern void VERS_SetVolPowerModeCfgSpacedByIdx(uint16 idx, uint8 val);
extern void VERS_GetVolPowerModeCfgSpaced(uint8 *buf, uint16 len);
extern uint8 *VERS_GetVolPowerModeCfgSpacedAddr(void);
extern uint8 VERS_GetVolPowerModeCfgSpacedByIdx(uint16 idx);

extern void VERS_SetLCMAModuleCfgLCMA_WarningLevel_1_Night(uint8 val);
extern uint8 VERS_GetLCMAModuleCfgLCMA_WarningLevel_1_Night(void);

extern void VERS_SetLCMAModuleCfgLCMA_WarningLevel_2_Night(uint8 val);
extern uint8 VERS_GetLCMAModuleCfgLCMA_WarningLevel_2_Night(void);

extern void VERS_SetLCMAModuleCfgLCMA_WarningLevel_1_Day(uint8 val);
extern uint8 VERS_GetLCMAModuleCfgLCMA_WarningLevel_1_Day(void);

extern void VERS_SetLCMAModuleCfgLCMA_WarningLevel_2_Day(uint8 val);
extern uint8 VERS_GetLCMAModuleCfgLCMA_WarningLevel_2_Day(void);

extern void VERS_SetLCMAModuleCfgLCMA_Min_WarningLevel_1(uint16 val);
extern uint16 VERS_GetLCMAModuleCfgLCMA_Min_WarningLevel_1(void);

extern void VERS_SetLCMAModuleCfgLCMA_Min_WarningLevel_2(uint16 val);
extern uint16 VERS_GetLCMAModuleCfgLCMA_Min_WarningLevel_2(void);

extern void VERS_SetLCMAModuleCfgLCMA_WarningLevel_2_OFF(uint16 val);
extern uint16 VERS_GetLCMAModuleCfgLCMA_WarningLevel_2_OFF(void);

extern void VERS_SetLCMAModuleCfgLCMA_WarningLevel_2_ON(uint16 val);
extern uint16 VERS_GetLCMAModuleCfgLCMA_WarningLevel_2_ON(void);

extern void VERS_SetDTCcontrolBitCfgBitData(const uint8 *buf, uint16 len);
extern void VERS_SetDTCcontrolBitCfgBitDataByIdx(uint16 idx, uint8 val);
extern void VERS_GetDTCcontrolBitCfgBitData(uint8 *buf, uint16 len);
extern uint8 *VERS_GetDTCcontrolBitCfgBitDataAddr(void);
extern uint8 VERS_GetDTCcontrolBitCfgBitDataByIdx(uint16 idx);

extern void VERS_SetMemPosUsrIDMemPos(const VERS_MemPos_t *buf, uint16 len);
extern void VERS_SetMemPosUsrIDMemPosByIdx(uint16 idx, VERS_MemPos_t val);
extern void VERS_GetMemPosUsrIDMemPos(VERS_MemPos_t *buf, uint16 len);
extern VERS_MemPos_t *VERS_GetMemPosUsrIDMemPosAddr(void);
extern VERS_MemPos_t VERS_GetMemPosUsrIDMemPosByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEMemBank1(const VERS_MemPos_Bank_t *buf, uint16 len);
extern void VERS_SetSR_PROFILEMemBank1ByIdx(uint16 idx, VERS_MemPos_Bank_t val);
extern void VERS_GetSR_PROFILEMemBank1(VERS_MemPos_Bank_t *buf, uint16 len);
extern VERS_MemPos_Bank_t *VERS_GetSR_PROFILEMemBank1Addr(void);
extern VERS_MemPos_Bank_t VERS_GetSR_PROFILEMemBank1ByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEMemBank2(const VERS_MemPos_Bank_t *buf, uint16 len);
extern void VERS_SetSR_PROFILEMemBank2ByIdx(uint16 idx, VERS_MemPos_Bank_t val);
extern void VERS_GetSR_PROFILEMemBank2(VERS_MemPos_Bank_t *buf, uint16 len);
extern VERS_MemPos_Bank_t *VERS_GetSR_PROFILEMemBank2Addr(void);
extern VERS_MemPos_Bank_t VERS_GetSR_PROFILEMemBank2ByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEMemBank3(const VERS_MemPos_Bank_t *buf, uint16 len);
extern void VERS_SetSR_PROFILEMemBank3ByIdx(uint16 idx, VERS_MemPos_Bank_t val);
extern void VERS_GetSR_PROFILEMemBank3(VERS_MemPos_Bank_t *buf, uint16 len);
extern VERS_MemPos_Bank_t *VERS_GetSR_PROFILEMemBank3Addr(void);
extern VERS_MemPos_Bank_t VERS_GetSR_PROFILEMemBank3ByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEAutoFoldCfgDrvr(const uint8 *buf, uint16 len);
extern void VERS_SetSR_PROFILEAutoFoldCfgDrvrByIdx(uint16 idx, uint8 val);
extern void VERS_GetSR_PROFILEAutoFoldCfgDrvr(uint8 *buf, uint16 len);
extern uint8 *VERS_GetSR_PROFILEAutoFoldCfgDrvrAddr(void);
extern uint8 VERS_GetSR_PROFILEAutoFoldCfgDrvrByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEAutoFoldCfgPass(const uint8 *buf, uint16 len);
extern void VERS_SetSR_PROFILEAutoFoldCfgPassByIdx(uint16 idx, uint8 val);
extern void VERS_GetSR_PROFILEAutoFoldCfgPass(uint8 *buf, uint16 len);
extern uint8 *VERS_GetSR_PROFILEAutoFoldCfgPassAddr(void);
extern uint8 VERS_GetSR_PROFILEAutoFoldCfgPassByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEAutoDipCfgDrvr(const uint8 *buf, uint16 len);
extern void VERS_SetSR_PROFILEAutoDipCfgDrvrByIdx(uint16 idx, uint8 val);
extern void VERS_GetSR_PROFILEAutoDipCfgDrvr(uint8 *buf, uint16 len);
extern uint8 *VERS_GetSR_PROFILEAutoDipCfgDrvrAddr(void);
extern uint8 VERS_GetSR_PROFILEAutoDipCfgDrvrByIdx(uint16 idx);

extern void VERS_SetSR_PROFILEAutoDipCfgPass(const uint8 *buf, uint16 len);
extern void VERS_SetSR_PROFILEAutoDipCfgPassByIdx(uint16 idx, uint8 val);
extern void VERS_GetSR_PROFILEAutoDipCfgPass(uint8 *buf, uint16 len);
extern uint8 *VERS_GetSR_PROFILEAutoDipCfgPassAddr(void);
extern uint8 VERS_GetSR_PROFILEAutoDipCfgPassByIdx(uint16 idx);

extern void VERS_SetMirrorStEEP_FoldSts(uint8 val);
extern uint8 VERS_GetMirrorStEEP_FoldSts(void);

extern void VERS_SetMirrorStEEP_MirrorHeatingAction(uint8 val);
extern uint8 VERS_GetMirrorStEEP_MirrorHeatingAction(void);

extern void VERS_SetMirrorStEEP_MaxMirrorAdjustTime(uint8 val);
extern uint8 VERS_GetMirrorStEEP_MaxMirrorAdjustTime(void);

extern void VERS_SetMirrorStEEP_MaxBlockRetryCounter(uint8 val);
extern uint8 VERS_GetMirrorStEEP_MaxBlockRetryCounter(void);

extern void VERS_SetMirrorStEEP_DynamicMirrorSts(uint8 val);
extern uint8 VERS_GetMirrorStEEP_DynamicMirrorSts(void);

extern void VERS_SetMirrorStEEP_ManualFold(uint8 val);
extern uint8 VERS_GetMirrorStEEP_ManualFold(void);

extern void VERS_SetMirrorStUntiltPosX(uint16 val);
extern uint16 VERS_GetMirrorStUntiltPosX(void);

extern void VERS_SetMirrorStUntiltPosY(uint16 val);
extern uint16 VERS_GetMirrorStUntiltPosY(void);

extern void VERS_SetMirrorStFoldPeak(uint16 val);
extern uint16 VERS_GetMirrorStFoldPeak(void);

extern void VERS_SetDTC_DATA_BLOCK1DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK1DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK1DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK1DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK1DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK2DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK2DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK2DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK2DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK2DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK3DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK3DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK3DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK3DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK3DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK4DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK4DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK4DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK4DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK4DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK5DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK5DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK5DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK5DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK5DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK6DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK6DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK6DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK6DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK6DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK7DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK7DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK7DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK7DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK7DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK8DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK8DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK8DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK8DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK8DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK9DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK9DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK9DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK9DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK9DTCBufByIdx(uint16 idx);

extern void VERS_SetDTC_DATA_BLOCK10DTCBuf(const VERS_DtcBlock_t *buf, uint16 len);
extern void VERS_SetDTC_DATA_BLOCK10DTCBufByIdx(uint16 idx, VERS_DtcBlock_t val);
extern void VERS_GetDTC_DATA_BLOCK10DTCBuf(VERS_DtcBlock_t *buf, uint16 len);
extern VERS_DtcBlock_t *VERS_GetDTC_DATA_BLOCK10DTCBufAddr(void);
extern VERS_DtcBlock_t VERS_GetDTC_DATA_BLOCK10DTCBufByIdx(uint16 idx);

extern void VERS_SetPMMEEP_GoToSleepTime(uint8 val);
extern uint8 VERS_GetPMMEEP_GoToSleepTime(void);

extern void VERS_SetPMMEEP_BCM_ATWS_ST(uint8 val);
extern uint8 VERS_GetPMMEEP_BCM_ATWS_ST(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_1(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_1(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_2(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_2(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_3(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_3(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_4(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_4(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_5(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_5(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_6(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_6(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_7(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_7(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_8(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_8(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_9(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_9(void);

extern void VERS_SetPMMEEP_WAKEUP_SRC_10(uint8 val);
extern uint8 VERS_GetPMMEEP_WAKEUP_SRC_10(void);

extern void VERS_SetPMMNmHisBuf(const uint8 *buf, uint16 len);
extern void VERS_SetPMMNmHisBufByIdx(uint16 idx, uint8 val);
extern void VERS_GetPMMNmHisBuf(uint8 *buf, uint16 len);
extern uint8 *VERS_GetPMMNmHisBufAddr(void);
extern uint8 VERS_GetPMMNmHisBufByIdx(uint16 idx);

extern void VERS_SetPMMNmHisBufIdx(uint16 val);
extern uint16 VERS_GetPMMNmHisBufIdx(void);

extern void VERS_SetSecurityAccessConfigSecurityAccessAtt(uint8 val);
extern uint8 VERS_GetSecurityAccessConfigSecurityAccessAtt(void);

extern void VERS_SetVehCfgHighQ_CurrFuncSts(uint8 val);
extern uint8 VERS_GetVehCfgHighQ_CurrFuncSts(void);

extern void VERS_SetCarCfgFaultyPara(const VERS_CarCfgPara_t *buf, uint16 len);
extern void VERS_SetCarCfgFaultyParaByIdx(uint16 idx, VERS_CarCfgPara_t val);
extern void VERS_GetCarCfgFaultyPara(VERS_CarCfgPara_t *buf, uint16 len);
extern VERS_CarCfgPara_t *VERS_GetCarCfgFaultyParaAddr(void);
extern VERS_CarCfgPara_t VERS_GetCarCfgFaultyParaByIdx(uint16 idx);

extern void VERS_SetCarCfgFaultyTotalNum(uint16 val);
extern uint16 VERS_GetCarCfgFaultyTotalNum(void);

extern void VERS_SetAPLearnApprenticeTable_ini(uint8 val);
extern uint8 VERS_GetAPLearnApprenticeTable_ini(void);

extern void VERS_SetAPLearnTorque_HighThreshold(uint8 val);
extern uint8 VERS_GetAPLearnTorque_HighThreshold(void);

extern void VERS_SetAPLearnTorque_LowThreshold(uint8 val);
extern uint8 VERS_GetAPLearnTorque_LowThreshold(void);

extern void VERS_SetAPLearnTorqueHard_HighThld(uint8 val);
extern uint8 VERS_GetAPLearnTorqueHard_HighThld(void);

extern void VERS_SetAPLearnTorqueHard_LowThld(uint8 val);
extern uint8 VERS_GetAPLearnTorqueHard_LowThld(void);

extern void VERS_SetAPLearnTorque_Ignore(uint8 val);
extern uint8 VERS_GetAPLearnTorque_Ignore(void);

extern void VERS_SetAPLearnWLCarto(const sint8 *buf, uint16 len);
extern void VERS_SetAPLearnWLCartoByIdx(uint16 idx, sint8 val);
extern void VERS_GetAPLearnWLCarto(sint8 *buf, uint16 len);
extern sint8 *VERS_GetAPLearnWLCartoAddr(void);
extern sint8 VERS_GetAPLearnWLCartoByIdx(uint16 idx);

extern void VERS_SetAPLearnVentUpStopCorrVal(const uint16 *buf, uint16 len);
extern void VERS_SetAPLearnVentUpStopCorrValByIdx(uint16 idx, uint16 val);
extern void VERS_GetAPLearnVentUpStopCorrVal(uint16 *buf, uint16 len);
extern uint16 *VERS_GetAPLearnVentUpStopCorrValAddr(void);
extern uint16 VERS_GetAPLearnVentUpStopCorrValByIdx(uint16 idx);

extern void VERS_SetAPLearnVentDownStopCorrVal(const uint16 *buf, uint16 len);
extern void VERS_SetAPLearnVentDownStopCorrValByIdx(uint16 idx, uint16 val);
extern void VERS_GetAPLearnVentDownStopCorrVal(uint16 *buf, uint16 len);
extern uint16 *VERS_GetAPLearnVentDownStopCorrValAddr(void);
extern uint16 VERS_GetAPLearnVentDownStopCorrValByIdx(uint16 idx);

extern void VERS_SetAPFilterStdAPCriterionThreshold10(const uint8 *buf, uint16 len);
extern void VERS_SetAPFilterStdAPCriterionThreshold10ByIdx(uint16 idx, uint8 val);
extern void VERS_GetAPFilterStdAPCriterionThreshold10(uint8 *buf, uint16 len);
extern uint8 *VERS_GetAPFilterStdAPCriterionThreshold10Addr(void);
extern uint8 VERS_GetAPFilterStdAPCriterionThreshold10ByIdx(uint16 idx);

extern void VERS_SetAPFilterStdAPCriterionThreshold12(const uint8 *buf, uint16 len);
extern void VERS_SetAPFilterStdAPCriterionThreshold12ByIdx(uint16 idx, uint8 val);
extern void VERS_GetAPFilterStdAPCriterionThreshold12(uint8 *buf, uint16 len);
extern uint8 *VERS_GetAPFilterStdAPCriterionThreshold12Addr(void);
extern uint8 VERS_GetAPFilterStdAPCriterionThreshold12ByIdx(uint16 idx);

extern void VERS_SetAPFilterStdAPCriterionThreshold14(const uint8 *buf, uint16 len);
extern void VERS_SetAPFilterStdAPCriterionThreshold14ByIdx(uint16 idx, uint8 val);
extern void VERS_GetAPFilterStdAPCriterionThreshold14(uint8 *buf, uint16 len);
extern uint8 *VERS_GetAPFilterStdAPCriterionThreshold14Addr(void);
extern uint8 VERS_GetAPFilterStdAPCriterionThreshold14ByIdx(uint16 idx);

extern void VERS_SetAPFilterStdAPCriterionThreshold16(const uint8 *buf, uint16 len);
extern void VERS_SetAPFilterStdAPCriterionThreshold16ByIdx(uint16 idx, uint8 val);
extern void VERS_GetAPFilterStdAPCriterionThreshold16(uint8 *buf, uint16 len);
extern uint8 *VERS_GetAPFilterStdAPCriterionThreshold16Addr(void);
extern uint8 VERS_GetAPFilterStdAPCriterionThreshold16ByIdx(uint16 idx);

extern void VERS_SetAPFilterTOR_BIAS(uint8 val);
extern uint8 VERS_GetAPFilterTOR_BIAS(void);

extern void VERS_SetAPFilterWayToApprenticeTable(uint8 val);
extern uint8 VERS_GetAPFilterWayToApprenticeTable(void);

extern void VERS_SetAPFilterWayToDegradationCriterion(uint8 val);
extern uint8 VERS_GetAPFilterWayToDegradationCriterion(void);

extern void VERS_SetAPFilterMaxGap(uint8 val);
extern uint8 VERS_GetAPFilterMaxGap(void);

extern void VERS_SetAPFilterWayToDegradationCriterionBBM(uint8 val);
extern uint8 VERS_GetAPFilterWayToDegradationCriterionBBM(void);

extern void VERS_SetAPFilterWidthOfWayToCalculateCriterion(uint8 val);
extern uint8 VERS_GetAPFilterWidthOfWayToCalculateCriterion(void);

extern void VERS_SetAPFilterTimeForMaxDetec(uint8 val);
extern uint8 VERS_GetAPFilterTimeForMaxDetec(void);

extern void VERS_SetAPFilterBlockTimeOut(uint8 val);
extern uint8 VERS_GetAPFilterBlockTimeOut(void);

extern void VERS_SetAPFilterWayToDegradationBelow(uint8 val);
extern uint8 VERS_GetAPFilterWayToDegradationBelow(void);

extern void VERS_SetAPFilterThresholdForBellowParam(uint8 val);
extern uint8 VERS_GetAPFilterThresholdForBellowParam(void);

extern void VERS_SetAPFilterHard_CriterionThreshold(sint8 val);
extern sint8 VERS_GetAPFilterHard_CriterionThreshold(void);

extern void VERS_SetAPFilterMaxForMaxDetec(uint16 val);
extern uint16 VERS_GetAPFilterMaxForMaxDetec(void);

extern void VERS_SetAPFilterMinForMaxDetec(uint16 val);
extern uint16 VERS_GetAPFilterMinForMaxDetec(void);

extern void VERS_SetWL_INIT_INFORNeverBeenInitialized_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORNeverBeenInitialized_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORNeverBeenInitialized_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORNeverBeenInitialized_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORNeverBeenInitialized_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR1_ExceedTimes_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR1_ExceedTimes_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR1_ExceedTimes_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR1_ExceedTimes_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR1_ExceedTimes_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR2_PowerOff_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR2_PowerOff_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR2_PowerOff_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR2_PowerOff_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR2_PowerOff_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR3_PosError_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR3_PosError_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR3_PosError_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR3_PosError_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR3_PosError_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR4_APOverride_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR4_APOverride_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR4_APOverride_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR4_APOverride_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR4_APOverride_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR5_Other1_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR5_Other1_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR5_Other1_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR5_Other1_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR5_Other1_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR6_Other2_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR6_Other2_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR6_Other2_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR6_Other2_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR6_Other2_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORSoftStopCounter_Cur(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORSoftStopCounter_CurByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORSoftStopCounter_Cur(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORSoftStopCounter_CurAddr(void);
extern uint8 VERS_GetWL_INIT_INFORSoftStopCounter_CurByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORNeverBeenInitialized_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORNeverBeenInitialized_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORNeverBeenInitialized_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORNeverBeenInitialized_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORNeverBeenInitialized_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR1_ExceedTimes_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR1_ExceedTimes_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR1_ExceedTimes_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR1_ExceedTimes_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR1_ExceedTimes_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR2_PowerOff_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR2_PowerOff_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR2_PowerOff_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR2_PowerOff_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR2_PowerOff_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR3_PosError_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR3_PosError_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR3_PosError_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR3_PosError_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR3_PosError_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR4_APOverride_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR4_APOverride_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR4_APOverride_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR4_APOverride_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR4_APOverride_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR5_Other1_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR5_Other1_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR5_Other1_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR5_Other1_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR5_Other1_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORR6_Other2_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORR6_Other2_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORR6_Other2_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORR6_Other2_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORR6_Other2_LastByIdx(uint16 idx);

extern void VERS_SetWL_INIT_INFORSoftStopCounter_Last(const uint8 *buf, uint16 len);
extern void VERS_SetWL_INIT_INFORSoftStopCounter_LastByIdx(uint16 idx, uint8 val);
extern void VERS_GetWL_INIT_INFORSoftStopCounter_Last(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWL_INIT_INFORSoftStopCounter_LastAddr(void);
extern uint8 VERS_GetWL_INIT_INFORSoftStopCounter_LastByIdx(uint16 idx);

extern void VERS_SetWLLOGLastKeyState(uint16 val);
extern uint16 VERS_GetWLLOGLastKeyState(void);

extern void VERS_SetWLLOGSaveAsUnInit(uint8 val);
extern uint8 VERS_GetWLLOGSaveAsUnInit(void);

extern void VERS_SetWLLOGSaveErrorTime(uint8 val);
extern uint8 VERS_GetWLLOGSaveErrorTime(void);

extern void VERS_SetWLLOGInitSateSaveTime(uint16 val);
extern uint16 VERS_GetWLLOGInitSateSaveTime(void);

extern void VERS_SetWLLOGMotorZeroPosition(uint16 val);
extern uint16 VERS_GetWLLOGMotorZeroPosition(void);

extern void VERS_SetWLLOGMotorSavePosition(uint16 val);
extern uint16 VERS_GetWLLOGMotorSavePosition(void);

extern void VERS_SetWLLOGMotorOutFramePosition(uint16 val);
extern uint16 VERS_GetWLLOGMotorOutFramePosition(void);

extern void VERS_SetWLLOGError3Position(uint16 val);
extern uint16 VERS_GetWLLOGError3Position(void);

extern void VERS_SetWLLOGWINMaxPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLLOGWINMaxPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLLOGWINMaxPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLLOGWINMaxPositionAddr(void);
extern uint16 VERS_GetWLLOGWINMaxPositionByIdx(uint16 idx);

extern void VERS_SetHandleCfgLastReprogrammingCounter(uint16 val);
extern uint16 VERS_GetHandleCfgLastReprogrammingCounter(void);

extern uint16 VERS_GetReprogrammingCounterValue(void);

extern void VERS_SetWLAPLogStacmdAction(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStacmdActionByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStacmdAction(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStacmdActionAddr(void);
extern uint8 VERS_GetWLAPLogStacmdActionByIdx(uint16 idx);

extern void VERS_SetWLAPLogStavoltage(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStavoltageByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStavoltage(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStavoltageAddr(void);
extern uint8 VERS_GetWLAPLogStavoltageByIdx(uint16 idx);

extern void VERS_SetWLAPLogStakeySts(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStakeyStsByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStakeySts(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStakeyStsAddr(void);
extern uint8 VERS_GetWLAPLogStakeyStsByIdx(uint16 idx);

extern void VERS_SetWLAPLogStabackEMFCnt(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStabackEMFCntByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStabackEMFCnt(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStabackEMFCntAddr(void);
extern uint8 VERS_GetWLAPLogStabackEMFCntByIdx(uint16 idx);

extern void VERS_SetWLAPLogStamaxPeriodRpctCnt(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStamaxPeriodRpctCntByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStamaxPeriodRpctCnt(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStamaxPeriodRpctCntAddr(void);
extern uint8 VERS_GetWLAPLogStamaxPeriodRpctCntByIdx(uint16 idx);

extern void VERS_SetWLAPLogStadelayPeakDetected(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStadelayPeakDetectedByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStadelayPeakDetected(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStadelayPeakDetectedAddr(void);
extern uint8 VERS_GetWLAPLogStadelayPeakDetectedByIdx(uint16 idx);

extern void VERS_SetWLAPLogStarunningTime(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStarunningTimeByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStarunningTime(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStarunningTimeAddr(void);
extern uint8 VERS_GetWLAPLogStarunningTimeByIdx(uint16 idx);

extern void VERS_SetWLAPLogStastartPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogStastartPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogStastartPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogStastartPositionAddr(void);
extern uint16 VERS_GetWLAPLogStastartPositionByIdx(uint16 idx);

extern void VERS_SetWLAPLogStaendPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogStaendPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogStaendPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogStaendPositionAddr(void);
extern uint16 VERS_GetWLAPLogStaendPositionByIdx(uint16 idx);

extern void VERS_SetWLAPLogStaBJTimeDateHour(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogStaBJTimeDateHourByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogStaBJTimeDateHour(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogStaBJTimeDateHourAddr(void);
extern uint16 VERS_GetWLAPLogStaBJTimeDateHourByIdx(uint16 idx);

extern void VERS_SetWLAPLogStaBJTimeMintSec(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogStaBJTimeMintSecByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogStaBJTimeMintSec(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogStaBJTimeMintSecAddr(void);
extern uint16 VERS_GetWLAPLogStaBJTimeMintSecByIdx(uint16 idx);

extern void VERS_SetWLAPLogStapowerOnTime(uint16 val);
extern uint16 VERS_GetWLAPLogStapowerOnTime(void);

extern void VERS_SetWLAPLogStaoperateIdx(uint8 val);
extern uint8 VERS_GetWLAPLogStaoperateIdx(void);

extern void VERS_SetWLAPLogStaSpared(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogStaSparedByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogStaSpared(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogStaSparedAddr(void);
extern uint8 VERS_GetWLAPLogStaSparedByIdx(uint16 idx);

extern void VERS_SetAPStopConfigMechHighEdgeHighThreshold(uint8 val);
extern uint8 VERS_GetAPStopConfigMechHighEdgeHighThreshold(void);

extern void VERS_SetAPStopConfigMechHighEdgeLowThreshold(uint8 val);
extern uint8 VERS_GetAPStopConfigMechHighEdgeLowThreshold(void);

extern void VERS_SetAPStopConfigMaxWdwLgth(uint16 val);
extern uint16 VERS_GetAPStopConfigMaxWdwLgth(void);

extern void VERS_SetAPStopConfigMechLowEdgeThreshold(uint8 val);
extern uint8 VERS_GetAPStopConfigMechLowEdgeThreshold(void);

extern void VERS_SetAPStopConfigThresholdBetweenMechAndSWLowEdge(uint8 val);
extern uint8 VERS_GetAPStopConfigThresholdBetweenMechAndSWLowEdge(void);

extern void VERS_SetAPStopConfigNumOfCycleOfLowSoftStop(uint8 val);
extern uint8 VERS_GetAPStopConfigNumOfCycleOfLowSoftStop(void);

extern void VERS_SetAPStopConfigReversalDist(uint8 val);
extern uint8 VERS_GetAPStopConfigReversalDist(void);

extern void VERS_SetAPStopConfigDeltaWdwLgth(uint8 val);
extern uint8 VERS_GetAPStopConfigDeltaWdwLgth(void);

extern void VERS_SetAPStopConfigSoftStpRelativePosit(uint8 val);
extern uint8 VERS_GetAPStopConfigSoftStpRelativePosit(void);

extern void VERS_SetAPStopConfigLowSoftStopConst(uint8 val);
extern uint8 VERS_GetAPStopConfigLowSoftStopConst(void);

extern void VERS_SetAPStopConfigHighSoftStopConst(uint8 val);
extern uint8 VERS_GetAPStopConfigHighSoftStopConst(void);

extern void VERS_SetAPStopConfigKineticCalcCst(uint8 val);
extern uint8 VERS_GetAPStopConfigKineticCalcCst(void);

extern void VERS_SetAPStopConfigCmdAuthoriDelay(uint8 val);
extern uint8 VERS_GetAPStopConfigCmdAuthoriDelay(void);

extern void VERS_SetAPStopConfigStaticCurrGrad(uint8 val);
extern uint8 VERS_GetAPStopConfigStaticCurrGrad(void);

extern void VERS_SetAPHardeningBCstFilter(uint8 val);
extern uint8 VERS_GetAPHardeningBCstFilter(void);

extern void VERS_SetAPHardeningBCstFilterBelow(uint8 val);
extern uint8 VERS_GetAPHardeningBCstFilterBelow(void);

extern void VERS_SetAPHardeningBwThreshold1(uint8 val);
extern uint8 VERS_GetAPHardeningBwThreshold1(void);

extern void VERS_SetAPHardeningBwThreshold2(uint8 val);
extern uint8 VERS_GetAPHardeningBwThreshold2(void);

extern void VERS_SetAPHardeningBwThreshold3(uint8 val);
extern uint8 VERS_GetAPHardeningBwThreshold3(void);

extern void VERS_SetAPHardeningBwVApCriterionOffset1(uint8 val);
extern uint8 VERS_GetAPHardeningBwVApCriterionOffset1(void);

extern void VERS_SetAPHardeningBwVApCriterionOffset2(uint8 val);
extern uint8 VERS_GetAPHardeningBwVApCriterionOffset2(void);

extern void VERS_SetAPHardeningBwVApCriterionOffset3(uint8 val);
extern uint8 VERS_GetAPHardeningBwVApCriterionOffset3(void);

extern void VERS_SetAPHardeningBwVTiming1(uint8 val);
extern uint8 VERS_GetAPHardeningBwVTiming1(void);

extern void VERS_SetAPHardeningBwVTiming2(uint8 val);
extern uint8 VERS_GetAPHardeningBwVTiming2(void);

extern void VERS_SetAPHardeningBwVTiming3(uint8 val);
extern uint8 VERS_GetAPHardeningBwVTiming3(void);

extern void VERS_SetAPHardeningk_BwV(uint8 val);
extern uint8 VERS_GetAPHardeningk_BwV(void);

extern void VERS_SetAPHardeningVoltFlucThreshold1(uint8 val);
extern uint8 VERS_GetAPHardeningVoltFlucThreshold1(void);

extern void VERS_SetAPHardeningVoltFlucThreshold2(uint8 val);
extern uint8 VERS_GetAPHardeningVoltFlucThreshold2(void);

extern void VERS_SetAPHardeningVoltFlucThreshold3(uint8 val);
extern uint8 VERS_GetAPHardeningVoltFlucThreshold3(void);

extern void VERS_SetAPHardeningNeg_Threshold_timing(uint8 val);
extern uint8 VERS_GetAPHardeningNeg_Threshold_timing(void);

extern void VERS_SetAPSealFstSealAPCriterionOffest(uint8 val);
extern uint8 VERS_GetAPSealFstSealAPCriterionOffest(void);

extern void VERS_SetAPSealFstWaySealDetec(uint8 val);
extern uint8 VERS_GetAPSealFstWaySealDetec(void);

extern void VERS_SetAPSealSndSealAPCriterionOffest(uint8 val);
extern uint8 VERS_GetAPSealSndSealAPCriterionOffest(void);

extern void VERS_SetAPSealSndWaySealDetec(uint8 val);
extern uint8 VERS_GetAPSealSndWaySealDetec(void);

extern void VERS_SetAPSealAPArea_LowThld(const uint16 *buf, uint16 len);
extern void VERS_SetAPSealAPArea_LowThldByIdx(uint16 idx, uint16 val);
extern void VERS_GetAPSealAPArea_LowThld(uint16 *buf, uint16 len);
extern uint16 *VERS_GetAPSealAPArea_LowThldAddr(void);
extern uint16 VERS_GetAPSealAPArea_LowThldByIdx(uint16 idx);

extern void VERS_SetAPSealSealPosition_ref(uint16 val);
extern uint16 VERS_GetAPSealSealPosition_ref(void);

extern void VERS_SetAPSealSealPosition_HighThreshold(uint8 val);
extern uint8 VERS_GetAPSealSealPosition_HighThreshold(void);

extern void VERS_SetAPSealSealPosition_LowThreshold(uint8 val);
extern uint8 VERS_GetAPSealSealPosition_LowThreshold(void);

extern void VERS_SetAPSealSealUpdateProcedure(uint8 val);
extern uint8 VERS_GetAPSealSealUpdateProcedure(void);

extern void VERS_SetAPSealStdSealThreshold(uint8 val);
extern uint8 VERS_GetAPSealStdSealThreshold(void);

extern void VERS_SetWLContextMotorPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLContextMotorPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLContextMotorPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLContextMotorPositionAddr(void);
extern uint16 VERS_GetWLContextMotorPositionByIdx(uint16 idx);

extern void VERS_SetWLContextLowSoftStopPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLContextLowSoftStopPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLContextLowSoftStopPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLContextLowSoftStopPositionAddr(void);
extern uint16 VERS_GetWLContextLowSoftStopPositionByIdx(uint16 idx);

extern void VERS_SetWLContextWdwInitState(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextWdwInitStateByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextWdwInitState(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextWdwInitStateAddr(void);
extern uint8 VERS_GetWLContextWdwInitStateByIdx(uint16 idx);

extern void VERS_SetWLContextPEPSHighBlockCounter(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextPEPSHighBlockCounterByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextPEPSHighBlockCounter(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextPEPSHighBlockCounterAddr(void);
extern uint8 VERS_GetWLContextPEPSHighBlockCounterByIdx(uint16 idx);

extern void VERS_SetWLContextLowSoftStopCnter(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextLowSoftStopCnterByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextLowSoftStopCnter(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextLowSoftStopCnterAddr(void);
extern uint8 VERS_GetWLContextLowSoftStopCnterByIdx(uint16 idx);

extern void VERS_SetWLContextHighSoftStopCnter(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextHighSoftStopCnterByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextHighSoftStopCnter(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextHighSoftStopCnterAddr(void);
extern uint8 VERS_GetWLContextHighSoftStopCnterByIdx(uint16 idx);

extern void VERS_SetWLContextWindowActivCnter(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextWindowActivCnterByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextWindowActivCnter(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextWindowActivCnterAddr(void);
extern uint8 VERS_GetWLContextWindowActivCnterByIdx(uint16 idx);

extern void VERS_SetWLContextSealPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLContextSealPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLContextSealPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLContextSealPositionAddr(void);
extern uint16 VERS_GetWLContextSealPositionByIdx(uint16 idx);

extern void VERS_SetWLContextLastStopPosition(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextLastStopPositionByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextLastStopPosition(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextLastStopPositionAddr(void);
extern uint8 VERS_GetWLContextLastStopPositionByIdx(uint16 idx);

extern void VERS_SetWLContextPositionStop(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextPositionStopByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextPositionStop(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextPositionStopAddr(void);
extern uint8 VERS_GetWLContextPositionStopByIdx(uint16 idx);

extern void VERS_SetWLContextLastKeyState(uint8 val);
extern uint8 VERS_GetWLContextLastKeyState(void);

extern void VERS_SetWLContextWLBlocking(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextWLBlockingByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextWLBlocking(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextWLBlockingAddr(void);
extern uint8 VERS_GetWLContextWLBlockingByIdx(uint16 idx);

extern void VERS_SetWLContextLowblockfinnish(const uint8 *buf, uint16 len);
extern void VERS_SetWLContextLowblockfinnishByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLContextLowblockfinnish(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLContextLowblockfinnishAddr(void);
extern uint8 VERS_GetWLContextLowblockfinnishByIdx(uint16 idx);

extern void VERS_SetWL_ProdConfigDoorMotorPolarity(uint8 val);
extern uint8 VERS_GetWL_ProdConfigDoorMotorPolarity(void);

extern void VERS_SetWL_ProdConfigTimeMechanicalEdge(uint8 val);
extern uint8 VERS_GetWL_ProdConfigTimeMechanicalEdge(void);

extern void VERS_SetWL_ProdConfigMaxNbrWithoutBlocking(uint8 val);
extern uint8 VERS_GetWL_ProdConfigMaxNbrWithoutBlocking(void);

extern void VERS_SetWL_ProdConfigTrialAmountWihtAPEnable(uint8 val);
extern uint8 VERS_GetWL_ProdConfigTrialAmountWihtAPEnable(void);

extern void VERS_SetAPConnexHighMechanicalEdge_HighThreshold(uint8 val);
extern uint8 VERS_GetAPConnexHighMechanicalEdge_HighThreshold(void);

extern void VERS_SetAPConnexHighMechanicalEdge_LowThreshold(uint8 val);
extern uint8 VERS_GetAPConnexHighMechanicalEdge_LowThreshold(void);

extern void VERS_SetAPConnexLowSoftStopConst(uint8 val);
extern uint8 VERS_GetAPConnexLowSoftStopConst(void);

extern void VERS_SetAPConnexKineticCalcCst(uint8 val);
extern uint8 VERS_GetAPConnexKineticCalcCst(void);

extern void VERS_SetAPConnexCmdAuthoriDelay(uint8 val);
extern uint8 VERS_GetAPConnexCmdAuthoriDelay(void);

extern void VERS_SetAPConnexMotorBrakCst(uint8 val);
extern uint8 VERS_GetAPConnexMotorBrakCst(void);

extern void VERS_SetAPConnexStaticCurrGrad(uint8 val);
extern uint8 VERS_GetAPConnexStaticCurrGrad(void);

extern void VERS_SetAPConnexReversalDist(uint16 val);
extern uint16 VERS_GetAPConnexReversalDist(void);

extern void VERS_SetAPConnexMaxWdwLgth(const uint16 *buf, uint16 len);
extern void VERS_SetAPConnexMaxWdwLgthByIdx(uint16 idx, uint16 val);
extern void VERS_GetAPConnexMaxWdwLgth(uint16 *buf, uint16 len);
extern uint16 *VERS_GetAPConnexMaxWdwLgthAddr(void);
extern uint16 VERS_GetAPConnexMaxWdwLgthByIdx(uint16 idx);

extern void VERS_SetAPConnexDeltaWdwLgth(uint16 val);
extern uint16 VERS_GetAPConnexDeltaWdwLgth(void);

extern void VERS_SetAPConnexSoftStpRelativePosit(const uint16 *buf, uint16 len);
extern void VERS_SetAPConnexSoftStpRelativePositByIdx(uint16 idx, uint16 val);
extern void VERS_GetAPConnexSoftStpRelativePosit(uint16 *buf, uint16 len);
extern uint16 *VERS_GetAPConnexSoftStpRelativePositAddr(void);
extern uint16 VERS_GetAPConnexSoftStpRelativePositByIdx(uint16 idx);

extern void VERS_SetWL_MC_DrvConfPWMCtrlEnable(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfPWMCtrlEnable(void);

extern void VERS_SetWL_MC_DrvConfPWMBattComp(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfPWMBattComp(void);

extern void VERS_SetWL_MC_DrvConfPWMDutyVal(uint16 val);
extern uint16 VERS_GetWL_MC_DrvConfPWMDutyVal(void);

extern void VERS_SetWL_MC_DrvConfAdjLowBlockStopEnable(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfAdjLowBlockStopEnable(void);

extern void VERS_SetWL_MC_DrvConfSStartEnable(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfSStartEnable(void);

extern void VERS_SetWL_MC_DrvConfSStartDutyVal(uint16 val);
extern uint16 VERS_GetWL_MC_DrvConfSStartDutyVal(void);

extern void VERS_SetWL_MC_DrvConfSStartIncStep(uint16 val);
extern uint16 VERS_GetWL_MC_DrvConfSStartIncStep(void);

extern void VERS_SetWL_MC_DrvConfSStartIncDly(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfSStartIncDly(void);

extern void VERS_SetWL_MC_DrvConfSStopEnable(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfSStopEnable(void);

extern void VERS_SetWL_MC_DrvConfSStopDutyVal(uint16 val);
extern uint16 VERS_GetWL_MC_DrvConfSStopDutyVal(void);

extern void VERS_SetWL_MC_DrvConfSStopDecStep(uint16 val);
extern uint16 VERS_GetWL_MC_DrvConfSStopDecStep(void);

extern void VERS_SetWL_MC_DrvConfSStopDecDly(uint8 val);
extern uint8 VERS_GetWL_MC_DrvConfSStopDecDly(void);

extern void VERS_SetWL_MC_DrvConfSStopStartPos(uint16 val);
extern uint16 VERS_GetWL_MC_DrvConfSStopStartPos(void);

extern void VERS_SetWLAPLogDymcmdAction(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymcmdActionByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymcmdAction(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymcmdActionAddr(void);
extern uint8 VERS_GetWLAPLogDymcmdActionByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymvoltage(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymvoltageByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymvoltage(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymvoltageAddr(void);
extern uint8 VERS_GetWLAPLogDymvoltageByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymkeySts(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymkeyStsByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymkeySts(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymkeyStsAddr(void);
extern uint8 VERS_GetWLAPLogDymkeyStsByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymbackEMFCnt(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymbackEMFCntByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymbackEMFCnt(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymbackEMFCntAddr(void);
extern uint8 VERS_GetWLAPLogDymbackEMFCntByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymmaxPeriodRpctCnt(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymmaxPeriodRpctCntByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymmaxPeriodRpctCnt(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymmaxPeriodRpctCntAddr(void);
extern uint8 VERS_GetWLAPLogDymmaxPeriodRpctCntByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymdelayPeakDetected(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymdelayPeakDetectedByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymdelayPeakDetected(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymdelayPeakDetectedAddr(void);
extern uint8 VERS_GetWLAPLogDymdelayPeakDetectedByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymrunningTime(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymrunningTimeByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymrunningTime(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymrunningTimeAddr(void);
extern uint8 VERS_GetWLAPLogDymrunningTimeByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymstartPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogDymstartPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogDymstartPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogDymstartPositionAddr(void);
extern uint16 VERS_GetWLAPLogDymstartPositionByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymendPosition(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogDymendPositionByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogDymendPosition(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogDymendPositionAddr(void);
extern uint16 VERS_GetWLAPLogDymendPositionByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymBJTimeDateHour(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogDymBJTimeDateHourByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogDymBJTimeDateHour(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogDymBJTimeDateHourAddr(void);
extern uint16 VERS_GetWLAPLogDymBJTimeDateHourByIdx(uint16 idx);

extern void VERS_SetWLAPLogDymBJTimeMintSec(const uint16 *buf, uint16 len);
extern void VERS_SetWLAPLogDymBJTimeMintSecByIdx(uint16 idx, uint16 val);
extern void VERS_GetWLAPLogDymBJTimeMintSec(uint16 *buf, uint16 len);
extern uint16 *VERS_GetWLAPLogDymBJTimeMintSecAddr(void);
extern uint16 VERS_GetWLAPLogDymBJTimeMintSecByIdx(uint16 idx);

extern void VERS_SetWLAPLogDympowerOnTime(uint16 val);
extern uint16 VERS_GetWLAPLogDympowerOnTime(void);

extern void VERS_SetWLAPLogDymoperateIdx(uint8 val);
extern uint8 VERS_GetWLAPLogDymoperateIdx(void);

extern void VERS_SetWLAPLogDymSpared(const uint8 *buf, uint16 len);
extern void VERS_SetWLAPLogDymSparedByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLAPLogDymSpared(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLAPLogDymSparedAddr(void);
extern uint8 VERS_GetWLAPLogDymSparedByIdx(uint16 idx);

extern void VERS_SetTHPAThermProtCnt(const uint16 *buf, uint16 len);
extern void VERS_SetTHPAThermProtCntByIdx(uint16 idx, uint16 val);
extern void VERS_GetTHPAThermProtCnt(uint16 *buf, uint16 len);
extern uint16 *VERS_GetTHPAThermProtCntAddr(void);
extern uint16 VERS_GetTHPAThermProtCntByIdx(uint16 idx);

extern void VERS_SetTHPAThermProtState(const uint8 *buf, uint16 len);
extern void VERS_SetTHPAThermProtStateByIdx(uint16 idx, uint8 val);
extern void VERS_GetTHPAThermProtState(uint8 *buf, uint16 len);
extern uint8 *VERS_GetTHPAThermProtStateAddr(void);
extern uint8 VERS_GetTHPAThermProtStateByIdx(uint16 idx);

extern void VERS_SetTHPANumOfUpActions(const uint8 *buf, uint16 len);
extern void VERS_SetTHPANumOfUpActionsByIdx(uint16 idx, uint8 val);
extern void VERS_GetTHPANumOfUpActions(uint8 *buf, uint16 len);
extern uint8 *VERS_GetTHPANumOfUpActionsAddr(void);
extern uint8 VERS_GetTHPANumOfUpActionsByIdx(uint16 idx);

extern void VERS_SetTHPANumOfDownActions(const uint8 *buf, uint16 len);
extern void VERS_SetTHPANumOfDownActionsByIdx(uint16 idx, uint8 val);
extern void VERS_GetTHPANumOfDownActions(uint8 *buf, uint16 len);
extern uint8 *VERS_GetTHPANumOfDownActionsAddr(void);
extern uint8 VERS_GetTHPANumOfDownActionsByIdx(uint16 idx);

extern void VERS_SetTHPAThermProtEnable(uint8 val);
extern uint8 VERS_GetTHPAThermProtEnable(void);

extern void VERS_SetTHPAWL_AutoLearnCnt(uint8 val);
extern uint8 VERS_GetTHPAWL_AutoLearnCnt(void);

extern void VERS_SetTHPAWL_ShortDropTime(uint8 val);
extern uint8 VERS_GetTHPAWL_ShortDropTime(void);

extern void VERS_SetTHPAPartialNetworkCluster(const uint8 *buf, uint16 len);
extern void VERS_SetTHPAPartialNetworkClusterByIdx(uint16 idx, uint8 val);
extern void VERS_GetTHPAPartialNetworkCluster(uint8 *buf, uint16 len);
extern uint8 *VERS_GetTHPAPartialNetworkClusterAddr(void);
extern uint8 VERS_GetTHPAPartialNetworkClusterByIdx(uint16 idx);

extern void VERS_SetTHPARoutineSelftestFailureReason(const uint8 *buf, uint16 len);
extern void VERS_SetTHPARoutineSelftestFailureReasonByIdx(uint16 idx, uint8 val);
extern void VERS_GetTHPARoutineSelftestFailureReason(uint8 *buf, uint16 len);
extern uint8 *VERS_GetTHPARoutineSelftestFailureReasonAddr(void);
extern uint8 VERS_GetTHPARoutineSelftestFailureReasonByIdx(uint16 idx);

extern void VERS_SetTHPAWL_Pinch(uint16 val);
extern uint16 VERS_GetTHPAWL_Pinch(void);

extern void VERS_SetTHPAWL_Close50Cnt(uint16 val);
extern uint16 VERS_GetTHPAWL_Close50Cnt(void);

extern void VERS_SetTHPAWL_ShortDropDist(uint16 val);
extern uint16 VERS_GetTHPAWL_ShortDropDist(void);

extern void VERS_SetTHPAWL_SmokGapUpperPosit(uint16 val);
extern uint16 VERS_GetTHPAWL_SmokGapUpperPosit(void);

extern void VERS_SetTHPAWL_SmokGapLowerPosit(uint16 val);
extern uint16 VERS_GetTHPAWL_SmokGapLowerPosit(void);

extern void VERS_SetTHPAWL_AutoLearnThreshold(uint16 val);
extern uint16 VERS_GetTHPAWL_AutoLearnThreshold(void);

extern void VERS_SetWLCEEP_MotorThermalPro_T1(uint16 val);
extern uint16 VERS_GetWLCEEP_MotorThermalPro_T1(void);

extern void VERS_SetWLCEEP_MotorThermalPro_T2(uint16 val);
extern uint16 VERS_GetWLCEEP_MotorThermalPro_T2(void);

extern void VERS_SetWLCEEP_LeftChildLockSts(uint8 val);
extern uint8 VERS_GetWLCEEP_LeftChildLockSts(void);

extern void VERS_SetWLCEEP_RightChildLockSts(uint8 val);
extern uint8 VERS_GetWLCEEP_RightChildLockSts(void);

extern void VERS_SetWLCShrtDrpFlg(uint8 val);
extern uint8 VERS_GetWLCShrtDrpFlg(void);

extern void VERS_SetWLCShortDropWinSts(uint8 val);
extern uint8 VERS_GetWLCShortDropWinSts(void);

extern void VERS_SetWLCWL_GlbDelayTime(const uint8 *buf, uint16 len);
extern void VERS_SetWLCWL_GlbDelayTimeByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLCWL_GlbDelayTime(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLCWL_GlbDelayTimeAddr(void);
extern uint8 VERS_GetWLCWL_GlbDelayTimeByIdx(uint16 idx);

extern void VERS_SetWLCWL_ManualSpeedUp(uint8 val);
extern uint8 VERS_GetWLCWL_ManualSpeedUp(void);

extern void VERS_SetWLCWL_ManualSpeedDown(uint8 val);
extern uint8 VERS_GetWLCWL_ManualSpeedDown(void);

extern void VERS_SetWLCWL_AutoSpeedUp(uint8 val);
extern uint8 VERS_GetWLCWL_AutoSpeedUp(void);

extern void VERS_SetWLCWL_AutoSpeedDown(uint8 val);
extern uint8 VERS_GetWLCWL_AutoSpeedDown(void);

extern void VERS_SetWLCWL_ManualAcclFromStop(uint8 val);
extern uint8 VERS_GetWLCWL_ManualAcclFromStop(void);

extern void VERS_SetWLCWL_AutoAcclFromStop(uint8 val);
extern uint8 VERS_GetWLCWL_AutoAcclFromStop(void);

extern void VERS_SetWLCWL_AcclManualToAuto(uint8 val);
extern uint8 VERS_GetWLCWL_AcclManualToAuto(void);

extern void VERS_SetWLCWL_ManualDecelFromStop(uint8 val);
extern uint8 VERS_GetWLCWL_ManualDecelFromStop(void);

extern void VERS_SetWLCWL_AutoDecelFromStop(uint8 val);
extern uint8 VERS_GetWLCWL_AutoDecelFromStop(void);

extern void VERS_SetWLCWL_DecelAutoToManual(uint8 val);
extern uint8 VERS_GetWLCWL_DecelAutoToManual(void);

extern void VERS_SetWLCWL_MaxVehSpeedFromOpen(uint8 val);
extern uint8 VERS_GetWLCWL_MaxVehSpeedFromOpen(void);

extern void VERS_SetWLCWL_PowerSoftstop(uint8 val);
extern uint8 VERS_GetWLCWL_PowerSoftstop(void);

extern void VERS_SetWLCWL_PowerPinchProtec(uint8 val);
extern uint8 VERS_GetWLCWL_PowerPinchProtec(void);

extern void VERS_SetWLCWL_PowerThermoProtec(uint8 val);
extern uint8 VERS_GetWLCWL_PowerThermoProtec(void);

extern void VERS_SetWLCWL_CycReinPeriodSoftstop(const uint8 *buf, uint16 len);
extern void VERS_SetWLCWL_CycReinPeriodSoftstopByIdx(uint16 idx, uint8 val);
extern void VERS_GetWLCWL_CycReinPeriodSoftstop(uint8 *buf, uint16 len);
extern uint8 *VERS_GetWLCWL_CycReinPeriodSoftstopAddr(void);
extern uint8 VERS_GetWLCWL_CycReinPeriodSoftstopByIdx(uint16 idx);

extern void VERS_SetWLCWL_AccelStopSmokAuto(uint8 val);
extern uint8 VERS_GetWLCWL_AccelStopSmokAuto(void);

extern void VERS_SetWLCWL_AccelFromSmokManu(uint8 val);
extern uint8 VERS_GetWLCWL_AccelFromSmokManu(void);

extern void VERS_SetWLCWL_DecelFromSmokToStop(uint8 val);
extern uint8 VERS_GetWLCWL_DecelFromSmokToStop(void);

extern void VERS_SetWLCWL_DecelFromManuToSmok(uint8 val);
extern uint8 VERS_GetWLCWL_DecelFromManuToSmok(void);

extern void VERS_SetWLCWL_FacFailReson(uint8 val);
extern uint8 VERS_GetWLCWL_FacFailReson(void);

extern void VERS_SetWLCWL_DoorSts(uint8 val);
extern uint8 VERS_GetWLCWL_DoorSts(void);

extern void VERS_SetWLCWL_AntiPinchCnt(uint16 val);
extern uint16 VERS_GetWLCWL_AntiPinchCnt(void);

extern void VERS_SetWLCWL_BlockCnt(uint16 val);
extern uint16 VERS_GetWLCWL_BlockCnt(void);

extern void VERS_SetWLCWL_Res(uint16 val);
extern uint16 VERS_GetWLCWL_Res(void);

extern void VERS_SetDLCChdPrtnLeftFailStsToHmi(uint8 val);
extern uint8 VERS_GetDLCChdPrtnLeftFailStsToHmi(void);

extern void VERS_SetDLCChdLockRightFailStsToHmi(uint8 val);
extern uint8 VERS_GetDLCChdLockRightFailStsToHmi(void);

extern void VERS_SetDLCChdPrtnLeftStsToHmi(uint8 val);
extern uint8 VERS_GetDLCChdPrtnLeftStsToHmi(void);

extern void VERS_SetDLCChdLockRightStsToHmi(uint8 val);
extern uint8 VERS_GetDLCChdLockRightStsToHmi(void);

extern void VERS_SetDLCChdPrtnLeftLedReq(uint8 val);
extern uint8 VERS_GetDLCChdPrtnLeftLedReq(void);

extern void VERS_SetDLCChdPrtnRightLedReq(uint8 val);
extern uint8 VERS_GetDLCChdPrtnRightLedReq(void);

extern void VERS_SetDLCChdLockLeftCmdFlag(uint8 val);
extern uint8 VERS_GetDLCChdLockLeftCmdFlag(void);

extern void VERS_SetDLCChdLockRightCmdFlag(uint8 val);
extern uint8 VERS_GetDLCChdLockRightCmdFlag(void);

extern void VERS_SetDLCWinDsblLeftCmd(uint8 val);
extern uint8 VERS_GetDLCWinDsblLeftCmd(void);

extern void VERS_SetDLCWinDsblRightCmd(uint8 val);
extern uint8 VERS_GetDLCWinDsblRightCmd(void);

extern void VERS_SetDLCCentralLockStatus(uint8 val);
extern uint8 VERS_GetDLCCentralLockStatus(void);

extern void VERS_SetDLCDoubleLockStatus(uint8 val);
extern uint8 VERS_GetDLCDoubleLockStatus(void);

extern void VERS_SetDLCChildLockStatus(uint8 val);
extern uint8 VERS_GetDLCChildLockStatus(void);

extern void VERS_SetDLCLockSwStatusLed(uint8 val);
extern uint8 VERS_GetDLCLockSwStatusLed(void);

extern void VERS_SetDLCDoorLockSts(uint8 val);
extern uint8 VERS_GetDLCDoorLockSts(void);

extern void VERS_SetDLCChdLockSts(uint8 val);
extern uint8 VERS_GetDLCChdLockSts(void);

extern void VERS_SetDLCDoorDrvrLockCmdFlag(uint8 val);
extern uint8 VERS_GetDLCDoorDrvrLockCmdFlag(void);

extern void VERS_SetDLCCrashUnlockFlag(uint8 val);
extern uint8 VERS_GetDLCCrashUnlockFlag(void);

extern void VERS_SetDLCCanLockBusy(uint8 val);
extern uint8 VERS_GetDLCCanLockBusy(void);

extern void VERS_SetDLCResetBitFailFlag(uint8 val);
extern uint8 VERS_GetDLCResetBitFailFlag(void);

extern void VERS_SetDLCLatchPosition(uint8 val);
extern uint8 VERS_GetDLCLatchPosition(void);

extern void VERS_SetQCM_FAULT_DATAVERS_QCM_Fault(const VERS_QCM_Fault_t *buf, uint16 len);
extern void VERS_SetQCM_FAULT_DATAVERS_QCM_FaultByIdx(uint16 idx, VERS_QCM_Fault_t val);
extern void VERS_GetQCM_FAULT_DATAVERS_QCM_Fault(VERS_QCM_Fault_t *buf, uint16 len);
extern VERS_QCM_Fault_t *VERS_GetQCM_FAULT_DATAVERS_QCM_FaultAddr(void);
extern VERS_QCM_Fault_t VERS_GetQCM_FAULT_DATAVERS_QCM_FaultByIdx(uint16 idx);

extern void VERS_SetQCM_FAULT_DATAQCMFaultBufIdx(uint8 val);
extern uint8 VERS_GetQCM_FAULT_DATAQCMFaultBufIdx(void);

extern void VERS_SetSysErrLogModule(const uint8 *buf, uint16 len);
extern void VERS_SetSysErrLogModuleByIdx(uint16 idx, uint8 val);
extern void VERS_GetSysErrLogModule(uint8 *buf, uint16 len);
extern uint8 *VERS_GetSysErrLogModuleAddr(void);
extern uint8 VERS_GetSysErrLogModuleByIdx(uint16 idx);

extern void VERS_SetSysErrLogCode(const uint8 *buf, uint16 len);
extern void VERS_SetSysErrLogCodeByIdx(uint16 idx, uint8 val);
extern void VERS_GetSysErrLogCode(uint8 *buf, uint16 len);
extern uint8 *VERS_GetSysErrLogCodeAddr(void);
extern uint8 VERS_GetSysErrLogCodeByIdx(uint16 idx);

extern void VERS_SetSysErrLogPara(const uint32 *buf, uint16 len);
extern void VERS_SetSysErrLogParaByIdx(uint16 idx, uint32 val);
extern void VERS_GetSysErrLogPara(uint32 *buf, uint16 len);
extern uint32 *VERS_GetSysErrLogParaAddr(void);
extern uint32 VERS_GetSysErrLogParaByIdx(uint16 idx);

extern void VERS_SetSysErrLogIdx(uint16 val);
extern uint16 VERS_GetSysErrLogIdx(void);


#endif
/*______ E N D _____ (vers_dynamic.h) ________________________________________*/

/*PRQA S 0777 --*/
/*PRQA S 0779 --*/
